#-------------------------------------------------
#
# Project created by QtCreator 2017-02-04T13:03:37
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = DownTube
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += main.cpp \
    maindownmedia.cpp

HEADERS  += \
    maindownmedia.h

FORMS    += \
    maindownmedia.ui

DISTFILES += \
    youtube-dl/test/parameters.json \
    youtube-dl/test/versions.json \
    youtube-dl/test/swftests/ArrayAccess.as \
    youtube-dl/test/swftests/ClassCall.as \
    youtube-dl/test/swftests/ClassConstruction.as \
    youtube-dl/test/swftests/ConstantInt.as \
    youtube-dl/test/swftests/ConstArrayAccess.as \
    youtube-dl/test/swftests/DictCall.as \
    youtube-dl/test/swftests/EqualsOperator.as \
    youtube-dl/test/swftests/LocalVars.as \
    youtube-dl/test/swftests/MemberAssignment.as \
    youtube-dl/test/swftests/NeOperator.as \
    youtube-dl/test/swftests/PrivateCall.as \
    youtube-dl/test/swftests/PrivateVoidCall.as \
    youtube-dl/test/swftests/StaticAssignment.as \
    youtube-dl/test/swftests/StaticRetrieval.as \
    youtube-dl/test/swftests/StringBasics.as \
    youtube-dl/test/swftests/StringCharCodeAt.as \
    youtube-dl/test/swftests/StringConversion.as \
    youtube-dl/youtube_dl/downloader/__init__.pyc \
    youtube-dl/youtube_dl/downloader/common.pyc \
    youtube-dl/youtube_dl/downloader/dash.pyc \
    youtube-dl/youtube_dl/downloader/external.pyc \
    youtube-dl/youtube_dl/downloader/f4m.pyc \
    youtube-dl/youtube_dl/downloader/fragment.pyc \
    youtube-dl/youtube_dl/downloader/hls.pyc \
    youtube-dl/youtube_dl/downloader/http.pyc \
    youtube-dl/youtube_dl/downloader/ism.pyc \
    youtube-dl/youtube_dl/downloader/rtmp.pyc \
    youtube-dl/youtube_dl/downloader/rtsp.pyc \
    youtube-dl/youtube_dl/extractor/__init__.pyc \
    youtube-dl/youtube_dl/extractor/abc.pyc \
    youtube-dl/youtube_dl/extractor/abcnews.pyc \
    youtube-dl/youtube_dl/extractor/abcotvs.pyc \
    youtube-dl/youtube_dl/extractor/academicearth.pyc \
    youtube-dl/youtube_dl/extractor/acast.pyc \
    youtube-dl/youtube_dl/extractor/addanime.pyc \
    youtube-dl/youtube_dl/extractor/adobepass.pyc \
    youtube-dl/youtube_dl/extractor/adobetv.pyc \
    youtube-dl/youtube_dl/extractor/adultswim.pyc \
    youtube-dl/youtube_dl/extractor/aenetworks.pyc \
    youtube-dl/youtube_dl/extractor/afreecatv.pyc \
    youtube-dl/youtube_dl/extractor/airmozilla.pyc \
    youtube-dl/youtube_dl/extractor/aljazeera.pyc \
    youtube-dl/youtube_dl/extractor/allocine.pyc \
    youtube-dl/youtube_dl/extractor/alphaporno.pyc \
    youtube-dl/youtube_dl/extractor/amcnetworks.pyc \
    youtube-dl/youtube_dl/extractor/amp.pyc \
    youtube-dl/youtube_dl/extractor/animeondemand.pyc \
    youtube-dl/youtube_dl/extractor/anitube.pyc \
    youtube-dl/youtube_dl/extractor/anvato.pyc \
    youtube-dl/youtube_dl/extractor/anysex.pyc \
    youtube-dl/youtube_dl/extractor/aol.pyc \
    youtube-dl/youtube_dl/extractor/aparat.pyc \
    youtube-dl/youtube_dl/extractor/appleconnect.pyc \
    youtube-dl/youtube_dl/extractor/appletrailers.pyc \
    youtube-dl/youtube_dl/extractor/archiveorg.pyc \
    youtube-dl/youtube_dl/extractor/ard.pyc \
    youtube-dl/youtube_dl/extractor/arkena.pyc \
    youtube-dl/youtube_dl/extractor/arte.pyc \
    youtube-dl/youtube_dl/extractor/atresplayer.pyc \
    youtube-dl/youtube_dl/extractor/atttechchannel.pyc \
    youtube-dl/youtube_dl/extractor/audimedia.pyc \
    youtube-dl/youtube_dl/extractor/audioboom.pyc \
    youtube-dl/youtube_dl/extractor/audiomack.pyc \
    youtube-dl/youtube_dl/extractor/awaan.pyc \
    youtube-dl/youtube_dl/extractor/azmedien.pyc \
    youtube-dl/youtube_dl/extractor/azubu.pyc \
    youtube-dl/youtube_dl/extractor/baidu.pyc \
    youtube-dl/youtube_dl/extractor/bambuser.pyc \
    youtube-dl/youtube_dl/extractor/bandcamp.pyc \
    youtube-dl/youtube_dl/extractor/bbc.pyc \
    youtube-dl/youtube_dl/extractor/beampro.pyc \
    youtube-dl/youtube_dl/extractor/beatport.pyc \
    youtube-dl/youtube_dl/extractor/beeg.pyc \
    youtube-dl/youtube_dl/extractor/behindkink.pyc \
    youtube-dl/youtube_dl/extractor/bellmedia.pyc \
    youtube-dl/youtube_dl/extractor/bet.pyc \
    youtube-dl/youtube_dl/extractor/bigflix.pyc \
    youtube-dl/youtube_dl/extractor/bild.pyc \
    youtube-dl/youtube_dl/extractor/bilibili.pyc \
    youtube-dl/youtube_dl/extractor/biobiochiletv.pyc \
    youtube-dl/youtube_dl/extractor/biqle.pyc \
    youtube-dl/youtube_dl/extractor/bleacherreport.pyc \
    youtube-dl/youtube_dl/extractor/blinkx.pyc \
    youtube-dl/youtube_dl/extractor/bloomberg.pyc \
    youtube-dl/youtube_dl/extractor/bokecc.pyc \
    youtube-dl/youtube_dl/extractor/bpb.pyc \
    youtube-dl/youtube_dl/extractor/br.pyc \
    youtube-dl/youtube_dl/extractor/bravotv.pyc \
    youtube-dl/youtube_dl/extractor/breakcom.pyc \
    youtube-dl/youtube_dl/extractor/brightcove.pyc \
    youtube-dl/youtube_dl/extractor/buzzfeed.pyc \
    youtube-dl/youtube_dl/extractor/byutv.pyc \
    youtube-dl/youtube_dl/extractor/c56.pyc \
    youtube-dl/youtube_dl/extractor/camdemy.pyc \
    youtube-dl/youtube_dl/extractor/camwithher.pyc \
    youtube-dl/youtube_dl/extractor/canalc2.pyc \
    youtube-dl/youtube_dl/extractor/canalplus.pyc \
    youtube-dl/youtube_dl/extractor/canvas.pyc \
    youtube-dl/youtube_dl/extractor/carambatv.pyc \
    youtube-dl/youtube_dl/extractor/cartoonnetwork.pyc \
    youtube-dl/youtube_dl/extractor/cbc.pyc \
    youtube-dl/youtube_dl/extractor/cbs.pyc \
    youtube-dl/youtube_dl/extractor/cbsinteractive.pyc \
    youtube-dl/youtube_dl/extractor/cbslocal.pyc \
    youtube-dl/youtube_dl/extractor/cbsnews.pyc \
    youtube-dl/youtube_dl/extractor/cbssports.pyc \
    youtube-dl/youtube_dl/extractor/ccc.pyc \
    youtube-dl/youtube_dl/extractor/ccma.pyc \
    youtube-dl/youtube_dl/extractor/cctv.pyc \
    youtube-dl/youtube_dl/extractor/cda.pyc \
    youtube-dl/youtube_dl/extractor/ceskatelevize.pyc \
    youtube-dl/youtube_dl/extractor/channel9.pyc \
    youtube-dl/youtube_dl/extractor/charlierose.pyc \
    youtube-dl/youtube_dl/extractor/chaturbate.pyc \
    youtube-dl/youtube_dl/extractor/chilloutzone.pyc \
    youtube-dl/youtube_dl/extractor/chirbit.pyc \
    youtube-dl/youtube_dl/extractor/cinchcast.pyc \
    youtube-dl/youtube_dl/extractor/clipfish.pyc \
    youtube-dl/youtube_dl/extractor/cliphunter.pyc \
    youtube-dl/youtube_dl/extractor/cliprs.pyc \
    youtube-dl/youtube_dl/extractor/clipsyndicate.pyc \
    youtube-dl/youtube_dl/extractor/closertotruth.pyc \
    youtube-dl/youtube_dl/extractor/cloudy.pyc \
    youtube-dl/youtube_dl/extractor/clubic.pyc \
    youtube-dl/youtube_dl/extractor/clyp.pyc \
    youtube-dl/youtube_dl/extractor/cmt.pyc \
    youtube-dl/youtube_dl/extractor/cnbc.pyc \
    youtube-dl/youtube_dl/extractor/cnn.pyc \
    youtube-dl/youtube_dl/extractor/collegerama.pyc \
    youtube-dl/youtube_dl/extractor/comcarcoff.pyc \
    youtube-dl/youtube_dl/extractor/comedycentral.pyc \
    youtube-dl/youtube_dl/extractor/common.pyc \
    youtube-dl/youtube_dl/extractor/commonmistakes.pyc \
    youtube-dl/youtube_dl/extractor/commonprotocols.pyc \
    youtube-dl/youtube_dl/extractor/condenast.pyc \
    youtube-dl/youtube_dl/extractor/corus.pyc \
    youtube-dl/youtube_dl/extractor/coub.pyc \
    youtube-dl/youtube_dl/extractor/cracked.pyc \
    youtube-dl/youtube_dl/extractor/crackle.pyc \
    youtube-dl/youtube_dl/extractor/criterion.pyc \
    youtube-dl/youtube_dl/extractor/crooksandliars.pyc \
    youtube-dl/youtube_dl/extractor/crunchyroll.pyc \
    youtube-dl/youtube_dl/extractor/cspan.pyc \
    youtube-dl/youtube_dl/extractor/ctsnews.pyc \
    youtube-dl/youtube_dl/extractor/ctvnews.pyc \
    youtube-dl/youtube_dl/extractor/cultureunplugged.pyc \
    youtube-dl/youtube_dl/extractor/curiositystream.pyc \
    youtube-dl/youtube_dl/extractor/cwtv.pyc \
    youtube-dl/youtube_dl/extractor/dailymail.pyc \
    youtube-dl/youtube_dl/extractor/dailymotion.pyc \
    youtube-dl/youtube_dl/extractor/daum.pyc \
    youtube-dl/youtube_dl/extractor/dbtv.pyc \
    youtube-dl/youtube_dl/extractor/dctp.pyc \
    youtube-dl/youtube_dl/extractor/deezer.pyc \
    youtube-dl/youtube_dl/extractor/defense.pyc \
    youtube-dl/youtube_dl/extractor/democracynow.pyc \
    youtube-dl/youtube_dl/extractor/dfb.pyc \
    youtube-dl/youtube_dl/extractor/dhm.pyc \
    youtube-dl/youtube_dl/extractor/digiteka.pyc \
    youtube-dl/youtube_dl/extractor/discovery.pyc \
    youtube-dl/youtube_dl/extractor/discoverygo.pyc \
    youtube-dl/youtube_dl/extractor/disney.pyc \
    youtube-dl/youtube_dl/extractor/dispeak.pyc \
    youtube-dl/youtube_dl/extractor/dotsub.pyc \
    youtube-dl/youtube_dl/extractor/douyutv.pyc \
    youtube-dl/youtube_dl/extractor/dplay.pyc \
    youtube-dl/youtube_dl/extractor/dramafever.pyc \
    youtube-dl/youtube_dl/extractor/drbonanza.pyc \
    youtube-dl/youtube_dl/extractor/dreisat.pyc \
    youtube-dl/youtube_dl/extractor/dropbox.pyc \
    youtube-dl/youtube_dl/extractor/drtuber.pyc \
    youtube-dl/youtube_dl/extractor/drtv.pyc \
    youtube-dl/youtube_dl/extractor/dumpert.pyc \
    youtube-dl/youtube_dl/extractor/dvtv.pyc \
    youtube-dl/youtube_dl/extractor/dw.pyc \
    youtube-dl/youtube_dl/extractor/eagleplatform.pyc \
    youtube-dl/youtube_dl/extractor/ebaumsworld.pyc \
    youtube-dl/youtube_dl/extractor/echomsk.pyc \
    youtube-dl/youtube_dl/extractor/egghead.pyc \
    youtube-dl/youtube_dl/extractor/ehow.pyc \
    youtube-dl/youtube_dl/extractor/eighttracks.pyc \
    youtube-dl/youtube_dl/extractor/einthusan.pyc \
    youtube-dl/youtube_dl/extractor/eitb.pyc \
    youtube-dl/youtube_dl/extractor/ellentv.pyc \
    youtube-dl/youtube_dl/extractor/elpais.pyc \
    youtube-dl/youtube_dl/extractor/embedly.pyc \
    youtube-dl/youtube_dl/extractor/engadget.pyc \
    youtube-dl/youtube_dl/extractor/eporner.pyc \
    youtube-dl/youtube_dl/extractor/eroprofile.pyc \
    youtube-dl/youtube_dl/extractor/escapist.pyc \
    youtube-dl/youtube_dl/extractor/espn.pyc \
    youtube-dl/youtube_dl/extractor/esri.pyc \
    youtube-dl/youtube_dl/extractor/europa.pyc \
    youtube-dl/youtube_dl/extractor/everyonesmixtape.pyc \
    youtube-dl/youtube_dl/extractor/expotv.pyc \
    youtube-dl/youtube_dl/extractor/extractors.pyc \
    youtube-dl/youtube_dl/extractor/extremetube.pyc \
    youtube-dl/youtube_dl/extractor/eyedotv.pyc \
    youtube-dl/youtube_dl/extractor/facebook.pyc \
    youtube-dl/youtube_dl/extractor/faz.pyc \
    youtube-dl/youtube_dl/extractor/fc2.pyc \
    youtube-dl/youtube_dl/extractor/fczenit.pyc \
    youtube-dl/youtube_dl/extractor/filmon.pyc \
    youtube-dl/youtube_dl/extractor/firstpost.pyc \
    youtube-dl/youtube_dl/extractor/firsttv.pyc \
    youtube-dl/youtube_dl/extractor/fivemin.pyc \
    youtube-dl/youtube_dl/extractor/fivetv.pyc \
    youtube-dl/youtube_dl/extractor/fktv.pyc \
    youtube-dl/youtube_dl/extractor/flickr.pyc \
    youtube-dl/youtube_dl/extractor/flipagram.pyc \
    youtube-dl/youtube_dl/extractor/folketinget.pyc \
    youtube-dl/youtube_dl/extractor/footyroom.pyc \
    youtube-dl/youtube_dl/extractor/formula1.pyc \
    youtube-dl/youtube_dl/extractor/fourtube.pyc \
    youtube-dl/youtube_dl/extractor/fox.pyc \
    youtube-dl/youtube_dl/extractor/fox9.pyc \
    youtube-dl/youtube_dl/extractor/foxgay.pyc \
    youtube-dl/youtube_dl/extractor/foxnews.pyc \
    youtube-dl/youtube_dl/extractor/foxsports.pyc \
    youtube-dl/youtube_dl/extractor/franceculture.pyc \
    youtube-dl/youtube_dl/extractor/franceinter.pyc \
    youtube-dl/youtube_dl/extractor/francetv.pyc \
    youtube-dl/youtube_dl/extractor/freesound.pyc \
    youtube-dl/youtube_dl/extractor/freespeech.pyc \
    youtube-dl/youtube_dl/extractor/funimation.pyc \
    youtube-dl/youtube_dl/extractor/funnyordie.pyc \
    youtube-dl/youtube_dl/extractor/fusion.pyc \
    youtube-dl/youtube_dl/extractor/fxnetworks.pyc \
    youtube-dl/youtube_dl/extractor/gameinformer.pyc \
    youtube-dl/youtube_dl/extractor/gameone.pyc \
    youtube-dl/youtube_dl/extractor/gamersyde.pyc \
    youtube-dl/youtube_dl/extractor/gamespot.pyc \
    youtube-dl/youtube_dl/extractor/gamestar.pyc \
    youtube-dl/youtube_dl/extractor/gaskrank.pyc \
    youtube-dl/youtube_dl/extractor/gazeta.pyc \
    youtube-dl/youtube_dl/extractor/gdcvault.pyc \
    youtube-dl/youtube_dl/extractor/generic.pyc \
    youtube-dl/youtube_dl/extractor/gfycat.pyc \
    youtube-dl/youtube_dl/extractor/giantbomb.pyc \
    youtube-dl/youtube_dl/extractor/giga.pyc \
    youtube-dl/youtube_dl/extractor/glide.pyc \
    youtube-dl/youtube_dl/extractor/globo.pyc \
    youtube-dl/youtube_dl/extractor/go.pyc \
    youtube-dl/youtube_dl/extractor/godtube.pyc \
    youtube-dl/youtube_dl/extractor/godtv.pyc \
    youtube-dl/youtube_dl/extractor/golem.pyc \
    youtube-dl/youtube_dl/extractor/googledrive.pyc \
    youtube-dl/youtube_dl/extractor/googleplus.pyc \
    youtube-dl/youtube_dl/extractor/googlesearch.pyc \
    youtube-dl/youtube_dl/extractor/goshgay.pyc \
    youtube-dl/youtube_dl/extractor/gputechconf.pyc \
    youtube-dl/youtube_dl/extractor/groupon.pyc \
    youtube-dl/youtube_dl/extractor/hark.pyc \
    youtube-dl/youtube_dl/extractor/hbo.pyc \
    youtube-dl/youtube_dl/extractor/hearthisat.pyc \
    youtube-dl/youtube_dl/extractor/heise.pyc \
    youtube-dl/youtube_dl/extractor/hellporno.pyc \
    youtube-dl/youtube_dl/extractor/helsinki.pyc \
    youtube-dl/youtube_dl/extractor/hentaistigma.pyc \
    youtube-dl/youtube_dl/extractor/hgtv.pyc \
    youtube-dl/youtube_dl/extractor/historicfilms.pyc \
    youtube-dl/youtube_dl/extractor/hitbox.pyc \
    youtube-dl/youtube_dl/extractor/hitrecord.pyc \
    youtube-dl/youtube_dl/extractor/hornbunny.pyc \
    youtube-dl/youtube_dl/extractor/hotnewhiphop.pyc \
    youtube-dl/youtube_dl/extractor/hotstar.pyc \
    youtube-dl/youtube_dl/extractor/howcast.pyc \
    youtube-dl/youtube_dl/extractor/howstuffworks.pyc \
    youtube-dl/youtube_dl/extractor/hrti.pyc \
    youtube-dl/youtube_dl/extractor/huajiao.pyc \
    youtube-dl/youtube_dl/extractor/huffpost.pyc \
    youtube-dl/youtube_dl/extractor/hypem.pyc \
    youtube-dl/youtube_dl/extractor/iconosquare.pyc \
    youtube-dl/youtube_dl/extractor/ign.pyc \
    youtube-dl/youtube_dl/extractor/imdb.pyc \
    youtube-dl/youtube_dl/extractor/imgur.pyc \
    youtube-dl/youtube_dl/extractor/ina.pyc \
    youtube-dl/youtube_dl/extractor/inc.pyc \
    youtube-dl/youtube_dl/extractor/indavideo.pyc \
    youtube-dl/youtube_dl/extractor/infoq.pyc \
    youtube-dl/youtube_dl/extractor/instagram.pyc \
    youtube-dl/youtube_dl/extractor/internetvideoarchive.pyc \
    youtube-dl/youtube_dl/extractor/iprima.pyc \
    youtube-dl/youtube_dl/extractor/iqiyi.pyc \
    youtube-dl/youtube_dl/extractor/ir90tv.pyc \
    youtube-dl/youtube_dl/extractor/itv.pyc \
    youtube-dl/youtube_dl/extractor/ivi.pyc \
    youtube-dl/youtube_dl/extractor/ivideon.pyc \
    youtube-dl/youtube_dl/extractor/iwara.pyc \
    youtube-dl/youtube_dl/extractor/izlesene.pyc \
    youtube-dl/youtube_dl/extractor/jamendo.pyc \
    youtube-dl/youtube_dl/extractor/jeuxvideo.pyc \
    youtube-dl/youtube_dl/extractor/jove.pyc \
    youtube-dl/youtube_dl/extractor/jpopsukitv.pyc \
    youtube-dl/youtube_dl/extractor/jwplatform.pyc \
    youtube-dl/youtube_dl/extractor/kaltura.pyc \
    youtube-dl/youtube_dl/extractor/kamcord.pyc \
    youtube-dl/youtube_dl/extractor/kanalplay.pyc \
    youtube-dl/youtube_dl/extractor/kankan.pyc \
    youtube-dl/youtube_dl/extractor/karaoketv.pyc \
    youtube-dl/youtube_dl/extractor/karrierevideos.pyc \
    youtube-dl/youtube_dl/extractor/keek.pyc \
    youtube-dl/youtube_dl/extractor/keezmovies.pyc \
    youtube-dl/youtube_dl/extractor/ketnet.pyc \
    youtube-dl/youtube_dl/extractor/khanacademy.pyc \
    youtube-dl/youtube_dl/extractor/kickstarter.pyc \
    youtube-dl/youtube_dl/extractor/konserthusetplay.pyc \
    youtube-dl/youtube_dl/extractor/kontrtube.pyc \
    youtube-dl/youtube_dl/extractor/krasview.pyc \
    youtube-dl/youtube_dl/extractor/ku6.pyc \
    youtube-dl/youtube_dl/extractor/kusi.pyc \
    youtube-dl/youtube_dl/extractor/kuwo.pyc \
    youtube-dl/youtube_dl/extractor/la7.pyc \
    youtube-dl/youtube_dl/extractor/laola1tv.pyc \
    youtube-dl/youtube_dl/extractor/lci.pyc \
    youtube-dl/youtube_dl/extractor/lcp.pyc \
    youtube-dl/youtube_dl/extractor/learnr.pyc \
    youtube-dl/youtube_dl/extractor/lecture2go.pyc \
    youtube-dl/youtube_dl/extractor/leeco.pyc \
    youtube-dl/youtube_dl/extractor/lego.pyc \
    youtube-dl/youtube_dl/extractor/lemonde.pyc \
    youtube-dl/youtube_dl/extractor/libraryofcongress.pyc \
    youtube-dl/youtube_dl/extractor/libsyn.pyc \
    youtube-dl/youtube_dl/extractor/lifenews.pyc \
    youtube-dl/youtube_dl/extractor/limelight.pyc \
    youtube-dl/youtube_dl/extractor/litv.pyc \
    youtube-dl/youtube_dl/extractor/liveleak.pyc \
    youtube-dl/youtube_dl/extractor/livestream.pyc \
    youtube-dl/youtube_dl/extractor/lnkgo.pyc \
    youtube-dl/youtube_dl/extractor/localnews8.pyc \
    youtube-dl/youtube_dl/extractor/lovehomeporn.pyc \
    youtube-dl/youtube_dl/extractor/lrt.pyc \
    youtube-dl/youtube_dl/extractor/lynda.pyc \
    youtube-dl/youtube_dl/extractor/m6.pyc \
    youtube-dl/youtube_dl/extractor/macgamestore.pyc \
    youtube-dl/youtube_dl/extractor/mailru.pyc \
    youtube-dl/youtube_dl/extractor/makerschannel.pyc \
    youtube-dl/youtube_dl/extractor/makertv.pyc \
    youtube-dl/youtube_dl/extractor/mangomolo.pyc \
    youtube-dl/youtube_dl/extractor/matchtv.pyc \
    youtube-dl/youtube_dl/extractor/mdr.pyc \
    youtube-dl/youtube_dl/extractor/meipai.pyc \
    youtube-dl/youtube_dl/extractor/melonvod.pyc \
    youtube-dl/youtube_dl/extractor/meta.pyc \
    youtube-dl/youtube_dl/extractor/metacafe.pyc \
    youtube-dl/youtube_dl/extractor/metacritic.pyc \
    youtube-dl/youtube_dl/extractor/mgoon.pyc \
    youtube-dl/youtube_dl/extractor/mgtv.pyc \
    youtube-dl/youtube_dl/extractor/miaopai.pyc \
    youtube-dl/youtube_dl/extractor/microsoftvirtualacademy.pyc \
    youtube-dl/youtube_dl/extractor/minhateca.pyc \
    youtube-dl/youtube_dl/extractor/ministrygrid.pyc \
    youtube-dl/youtube_dl/extractor/minoto.pyc \
    youtube-dl/youtube_dl/extractor/miomio.pyc \
    youtube-dl/youtube_dl/extractor/mit.pyc \
    youtube-dl/youtube_dl/extractor/mitele.pyc \
    youtube-dl/youtube_dl/extractor/mixcloud.pyc \
    youtube-dl/youtube_dl/extractor/mlb.pyc \
    youtube-dl/youtube_dl/extractor/mnet.pyc \
    youtube-dl/youtube_dl/extractor/moevideo.pyc \
    youtube-dl/youtube_dl/extractor/mofosex.pyc \
    youtube-dl/youtube_dl/extractor/mojvideo.pyc \
    youtube-dl/youtube_dl/extractor/moniker.pyc \
    youtube-dl/youtube_dl/extractor/morningstar.pyc \
    youtube-dl/youtube_dl/extractor/motherless.pyc \
    youtube-dl/youtube_dl/extractor/motorsport.pyc \
    youtube-dl/youtube_dl/extractor/movieclips.pyc \
    youtube-dl/youtube_dl/extractor/moviezine.pyc \
    youtube-dl/youtube_dl/extractor/movingimage.pyc \
    youtube-dl/youtube_dl/extractor/mpora.pyc \
    youtube-dl/youtube_dl/extractor/msn.pyc \
    youtube-dl/youtube_dl/extractor/mtv.pyc \
    youtube-dl/youtube_dl/extractor/muenchentv.pyc \
    youtube-dl/youtube_dl/extractor/musicplayon.pyc \
    youtube-dl/youtube_dl/extractor/mwave.pyc \
    youtube-dl/youtube_dl/extractor/myspace.pyc \
    youtube-dl/youtube_dl/extractor/myspass.pyc \
    youtube-dl/youtube_dl/extractor/myvi.pyc \
    youtube-dl/youtube_dl/extractor/myvideo.pyc \
    youtube-dl/youtube_dl/extractor/myvidster.pyc \
    youtube-dl/youtube_dl/extractor/nationalgeographic.pyc \
    youtube-dl/youtube_dl/extractor/naver.pyc \
    youtube-dl/youtube_dl/extractor/nba.pyc \
    youtube-dl/youtube_dl/extractor/nbc.pyc \
    youtube-dl/youtube_dl/extractor/ndr.pyc \
    youtube-dl/youtube_dl/extractor/ndtv.pyc \
    youtube-dl/youtube_dl/extractor/nerdcubed.pyc \
    youtube-dl/youtube_dl/extractor/neteasemusic.pyc \
    youtube-dl/youtube_dl/extractor/netzkino.pyc \
    youtube-dl/youtube_dl/extractor/newgrounds.pyc \
    youtube-dl/youtube_dl/extractor/newstube.pyc \
    youtube-dl/youtube_dl/extractor/nextmedia.pyc \
    youtube-dl/youtube_dl/extractor/nfb.pyc \
    youtube-dl/youtube_dl/extractor/nfl.pyc \
    youtube-dl/youtube_dl/extractor/nhk.pyc \
    youtube-dl/youtube_dl/extractor/nhl.pyc \
    youtube-dl/youtube_dl/extractor/nick.pyc \
    youtube-dl/youtube_dl/extractor/niconico.pyc \
    youtube-dl/youtube_dl/extractor/ninecninemedia.pyc \
    youtube-dl/youtube_dl/extractor/ninegag.pyc \
    youtube-dl/youtube_dl/extractor/ninenow.pyc \
    youtube-dl/youtube_dl/extractor/nintendo.pyc \
    youtube-dl/youtube_dl/extractor/nobelprize.pyc \
    youtube-dl/youtube_dl/extractor/noco.pyc \
    youtube-dl/youtube_dl/extractor/normalboots.pyc \
    youtube-dl/youtube_dl/extractor/nosvideo.pyc \
    youtube-dl/youtube_dl/extractor/nova.pyc \
    youtube-dl/youtube_dl/extractor/novamov.pyc \
    youtube-dl/youtube_dl/extractor/nowness.pyc \
    youtube-dl/youtube_dl/extractor/nowtv.pyc \
    youtube-dl/youtube_dl/extractor/noz.pyc \
    youtube-dl/youtube_dl/extractor/npo.pyc \
    youtube-dl/youtube_dl/extractor/npr.pyc \
    youtube-dl/youtube_dl/extractor/nrk.pyc \
    youtube-dl/youtube_dl/extractor/ntvde.pyc \
    youtube-dl/youtube_dl/extractor/ntvru.pyc \
    youtube-dl/youtube_dl/extractor/nuevo.pyc \
    youtube-dl/youtube_dl/extractor/nuvid.pyc \
    youtube-dl/youtube_dl/extractor/nytimes.pyc \
    youtube-dl/youtube_dl/extractor/nzz.pyc \
    youtube-dl/youtube_dl/extractor/odatv.pyc \
    youtube-dl/youtube_dl/extractor/odnoklassniki.pyc \
    youtube-dl/youtube_dl/extractor/oktoberfesttv.pyc \
    youtube-dl/youtube_dl/extractor/once.pyc \
    youtube-dl/youtube_dl/extractor/ondemandkorea.pyc \
    youtube-dl/youtube_dl/extractor/onet.pyc \
    youtube-dl/youtube_dl/extractor/onionstudios.pyc \
    youtube-dl/youtube_dl/extractor/ooyala.pyc \
    youtube-dl/youtube_dl/extractor/openload.pyc \
    youtube-dl/youtube_dl/extractor/ora.pyc \
    youtube-dl/youtube_dl/extractor/orf.pyc \
    youtube-dl/youtube_dl/extractor/pandatv.pyc \
    youtube-dl/youtube_dl/extractor/pandoratv.pyc \
    youtube-dl/youtube_dl/extractor/parliamentliveuk.pyc \
    youtube-dl/youtube_dl/extractor/patreon.pyc \
    youtube-dl/youtube_dl/extractor/pbs.pyc \
    youtube-dl/youtube_dl/extractor/people.pyc \
    youtube-dl/youtube_dl/extractor/periscope.pyc \
    youtube-dl/youtube_dl/extractor/philharmoniedeparis.pyc \
    youtube-dl/youtube_dl/extractor/phoenix.pyc \
    youtube-dl/youtube_dl/extractor/photobucket.pyc \
    youtube-dl/youtube_dl/extractor/piksel.pyc \
    youtube-dl/youtube_dl/extractor/pinkbike.pyc \
    youtube-dl/youtube_dl/extractor/pladform.pyc \
    youtube-dl/youtube_dl/extractor/playfm.pyc \
    youtube-dl/youtube_dl/extractor/plays.pyc \
    youtube-dl/youtube_dl/extractor/playtvak.pyc \
    youtube-dl/youtube_dl/extractor/playvid.pyc \
    youtube-dl/youtube_dl/extractor/playwire.pyc \
    youtube-dl/youtube_dl/extractor/pluralsight.pyc \
    youtube-dl/youtube_dl/extractor/podomatic.pyc \
    youtube-dl/youtube_dl/extractor/pokemon.pyc \
    youtube-dl/youtube_dl/extractor/polskieradio.pyc \
    youtube-dl/youtube_dl/extractor/porn91.pyc \
    youtube-dl/youtube_dl/extractor/porncom.pyc \
    youtube-dl/youtube_dl/extractor/pornflip.pyc \
    youtube-dl/youtube_dl/extractor/pornhd.pyc \
    youtube-dl/youtube_dl/extractor/pornhub.pyc \
    youtube-dl/youtube_dl/extractor/pornotube.pyc \
    youtube-dl/youtube_dl/extractor/pornovoisines.pyc \
    youtube-dl/youtube_dl/extractor/pornoxo.pyc \
    youtube-dl/youtube_dl/extractor/presstv.pyc \
    youtube-dl/youtube_dl/extractor/primesharetv.pyc \
    youtube-dl/youtube_dl/extractor/promptfile.pyc \
    youtube-dl/youtube_dl/extractor/prosiebensat1.pyc \
    youtube-dl/youtube_dl/extractor/puls4.pyc \
    youtube-dl/youtube_dl/extractor/pyvideo.pyc \
    youtube-dl/youtube_dl/extractor/qqmusic.pyc \
    youtube-dl/youtube_dl/extractor/r7.pyc \
    youtube-dl/youtube_dl/extractor/radiobremen.pyc \
    youtube-dl/youtube_dl/extractor/radiocanada.pyc \
    youtube-dl/youtube_dl/extractor/radiode.pyc \
    youtube-dl/youtube_dl/extractor/radiofrance.pyc \
    youtube-dl/youtube_dl/extractor/radiojavan.pyc \
    youtube-dl/youtube_dl/extractor/rai.pyc \
    youtube-dl/youtube_dl/extractor/rbmaradio.pyc \
    youtube-dl/youtube_dl/extractor/rds.pyc \
    youtube-dl/youtube_dl/extractor/redtube.pyc \
    youtube-dl/youtube_dl/extractor/regiotv.pyc \
    youtube-dl/youtube_dl/extractor/rentv.pyc \
    youtube-dl/youtube_dl/extractor/restudy.pyc \
    youtube-dl/youtube_dl/extractor/reuters.pyc \
    youtube-dl/youtube_dl/extractor/reverbnation.pyc \
    youtube-dl/youtube_dl/extractor/revision3.pyc \
    youtube-dl/youtube_dl/extractor/rice.pyc \
    youtube-dl/youtube_dl/extractor/ringtv.pyc \
    youtube-dl/youtube_dl/extractor/rmcdecouverte.pyc \
    youtube-dl/youtube_dl/extractor/ro220.pyc \
    youtube-dl/youtube_dl/extractor/rockstargames.pyc \
    youtube-dl/youtube_dl/extractor/roosterteeth.pyc \
    youtube-dl/youtube_dl/extractor/rottentomatoes.pyc \
    youtube-dl/youtube_dl/extractor/roxwel.pyc \
    youtube-dl/youtube_dl/extractor/rozhlas.pyc \
    youtube-dl/youtube_dl/extractor/rtbf.pyc \
    youtube-dl/youtube_dl/extractor/rte.pyc \
    youtube-dl/youtube_dl/extractor/rtl2.pyc \
    youtube-dl/youtube_dl/extractor/rtlnl.pyc \
    youtube-dl/youtube_dl/extractor/rtp.pyc \
    youtube-dl/youtube_dl/extractor/rts.pyc \
    youtube-dl/youtube_dl/extractor/rtve.pyc \
    youtube-dl/youtube_dl/extractor/rtvnh.pyc \
    youtube-dl/youtube_dl/extractor/rudo.pyc \
    youtube-dl/youtube_dl/extractor/ruhd.pyc \
    youtube-dl/youtube_dl/extractor/ruleporn.pyc \
    youtube-dl/youtube_dl/extractor/rutube.pyc \
    youtube-dl/youtube_dl/extractor/rutv.pyc \
    youtube-dl/youtube_dl/extractor/ruutu.pyc \
    youtube-dl/youtube_dl/extractor/safari.pyc \
    youtube-dl/youtube_dl/extractor/sandia.pyc \
    youtube-dl/youtube_dl/extractor/sapo.pyc \
    youtube-dl/youtube_dl/extractor/savefrom.pyc \
    youtube-dl/youtube_dl/extractor/sbs.pyc \
    youtube-dl/youtube_dl/extractor/scivee.pyc \
    youtube-dl/youtube_dl/extractor/screencast.pyc \
    youtube-dl/youtube_dl/extractor/screencastomatic.pyc \
    youtube-dl/youtube_dl/extractor/scrippsnetworks.pyc \
    youtube-dl/youtube_dl/extractor/seeker.pyc \
    youtube-dl/youtube_dl/extractor/senateisvp.pyc \
    youtube-dl/youtube_dl/extractor/sendtonews.pyc \
    youtube-dl/youtube_dl/extractor/servingsys.pyc \
    youtube-dl/youtube_dl/extractor/sexu.pyc \
    youtube-dl/youtube_dl/extractor/shahid.pyc \
    youtube-dl/youtube_dl/extractor/shared.pyc \
    youtube-dl/youtube_dl/extractor/showroomlive.pyc \
    youtube-dl/youtube_dl/extractor/sina.pyc \
    youtube-dl/youtube_dl/extractor/sixplay.pyc \
    youtube-dl/youtube_dl/extractor/skynewsarabia.pyc \
    youtube-dl/youtube_dl/extractor/skysports.pyc \
    youtube-dl/youtube_dl/extractor/slideshare.pyc \
    youtube-dl/youtube_dl/extractor/slutload.pyc \
    youtube-dl/youtube_dl/extractor/smotri.pyc \
    youtube-dl/youtube_dl/extractor/snotr.pyc \
    youtube-dl/youtube_dl/extractor/sohu.pyc \
    youtube-dl/youtube_dl/extractor/sonyliv.pyc \
    youtube-dl/youtube_dl/extractor/soundcloud.pyc \
    youtube-dl/youtube_dl/extractor/soundgasm.pyc \
    youtube-dl/youtube_dl/extractor/southpark.pyc \
    youtube-dl/youtube_dl/extractor/spankbang.pyc \
    youtube-dl/youtube_dl/extractor/spankwire.pyc \
    youtube-dl/youtube_dl/extractor/spiegel.pyc \
    youtube-dl/youtube_dl/extractor/spiegeltv.pyc \
    youtube-dl/youtube_dl/extractor/spike.pyc \
    youtube-dl/youtube_dl/extractor/sport5.pyc \
    youtube-dl/youtube_dl/extractor/sportbox.pyc \
    youtube-dl/youtube_dl/extractor/sportdeutschland.pyc \
    youtube-dl/youtube_dl/extractor/sportschau.pyc \
    youtube-dl/youtube_dl/extractor/sprout.pyc \
    youtube-dl/youtube_dl/extractor/srgssr.pyc \
    youtube-dl/youtube_dl/extractor/srmediathek.pyc \
    youtube-dl/youtube_dl/extractor/stanfordoc.pyc \
    youtube-dl/youtube_dl/extractor/steam.pyc \
    youtube-dl/youtube_dl/extractor/stitcher.pyc \
    youtube-dl/youtube_dl/extractor/streamable.pyc \
    youtube-dl/youtube_dl/extractor/streamcloud.pyc \
    youtube-dl/youtube_dl/extractor/streamcz.pyc \
    youtube-dl/youtube_dl/extractor/streetvoice.pyc \
    youtube-dl/youtube_dl/extractor/sunporno.pyc \
    youtube-dl/youtube_dl/extractor/svt.pyc \
    youtube-dl/youtube_dl/extractor/swrmediathek.pyc \
    youtube-dl/youtube_dl/extractor/syfy.pyc \
    youtube-dl/youtube_dl/extractor/sztvhu.pyc \
    youtube-dl/youtube_dl/extractor/tagesschau.pyc \
    youtube-dl/youtube_dl/extractor/tass.pyc \
    youtube-dl/youtube_dl/extractor/tbs.pyc \
    youtube-dl/youtube_dl/extractor/tdslifeway.pyc \
    youtube-dl/youtube_dl/extractor/teachertube.pyc \
    youtube-dl/youtube_dl/extractor/teachingchannel.pyc \
    youtube-dl/youtube_dl/extractor/teamcoco.pyc \
    youtube-dl/youtube_dl/extractor/teamfourstar.pyc \
    youtube-dl/youtube_dl/extractor/techtalks.pyc \
    youtube-dl/youtube_dl/extractor/ted.pyc \
    youtube-dl/youtube_dl/extractor/tele13.pyc \
    youtube-dl/youtube_dl/extractor/telebruxelles.pyc \
    youtube-dl/youtube_dl/extractor/telecinco.pyc \
    youtube-dl/youtube_dl/extractor/telegraaf.pyc \
    youtube-dl/youtube_dl/extractor/telemb.pyc \
    youtube-dl/youtube_dl/extractor/telequebec.pyc \
    youtube-dl/youtube_dl/extractor/teletask.pyc \
    youtube-dl/youtube_dl/extractor/telewebion.pyc \
    youtube-dl/youtube_dl/extractor/testurl.pyc \
    youtube-dl/youtube_dl/extractor/tf1.pyc \
    youtube-dl/youtube_dl/extractor/tfo.pyc \
    youtube-dl/youtube_dl/extractor/theintercept.pyc \
    youtube-dl/youtube_dl/extractor/theplatform.pyc \
    youtube-dl/youtube_dl/extractor/thescene.pyc \
    youtube-dl/youtube_dl/extractor/thesixtyone.pyc \
    youtube-dl/youtube_dl/extractor/thestar.pyc \
    youtube-dl/youtube_dl/extractor/theweatherchannel.pyc \
    youtube-dl/youtube_dl/extractor/thisamericanlife.pyc \
    youtube-dl/youtube_dl/extractor/thisav.pyc \
    youtube-dl/youtube_dl/extractor/thisoldhouse.pyc \
    youtube-dl/youtube_dl/extractor/threeqsdn.pyc \
    youtube-dl/youtube_dl/extractor/tinypic.pyc \
    youtube-dl/youtube_dl/extractor/tlc.pyc \
    youtube-dl/youtube_dl/extractor/tmz.pyc \
    youtube-dl/youtube_dl/extractor/tnaflix.pyc \
    youtube-dl/youtube_dl/extractor/toggle.pyc \
    youtube-dl/youtube_dl/extractor/tonline.pyc \
    youtube-dl/youtube_dl/extractor/toutv.pyc \
    youtube-dl/youtube_dl/extractor/toypics.pyc \
    youtube-dl/youtube_dl/extractor/traileraddict.pyc \
    youtube-dl/youtube_dl/extractor/trilulilu.pyc \
    youtube-dl/youtube_dl/extractor/trutv.pyc \
    youtube-dl/youtube_dl/extractor/tube8.pyc \
    youtube-dl/youtube_dl/extractor/tubitv.pyc \
    youtube-dl/youtube_dl/extractor/tudou.pyc \
    youtube-dl/youtube_dl/extractor/tumblr.pyc \
    youtube-dl/youtube_dl/extractor/tunein.pyc \
    youtube-dl/youtube_dl/extractor/turbo.pyc \
    youtube-dl/youtube_dl/extractor/turner.pyc \
    youtube-dl/youtube_dl/extractor/tutv.pyc \
    youtube-dl/youtube_dl/extractor/tv2.pyc \
    youtube-dl/youtube_dl/extractor/tv3.pyc \
    youtube-dl/youtube_dl/extractor/tv4.pyc \
    youtube-dl/youtube_dl/extractor/tva.pyc \
    youtube-dl/youtube_dl/extractor/tvanouvelles.pyc \
    youtube-dl/youtube_dl/extractor/tvc.pyc \
    youtube-dl/youtube_dl/extractor/tvigle.pyc \
    youtube-dl/youtube_dl/extractor/tvland.pyc \
    youtube-dl/youtube_dl/extractor/tvnoe.pyc \
    youtube-dl/youtube_dl/extractor/tvp.pyc \
    youtube-dl/youtube_dl/extractor/tvplay.pyc \
    youtube-dl/youtube_dl/extractor/tvplayer.pyc \
    youtube-dl/youtube_dl/extractor/tweakers.pyc \
    youtube-dl/youtube_dl/extractor/twentyfourvideo.pyc \
    youtube-dl/youtube_dl/extractor/twentymin.pyc \
    youtube-dl/youtube_dl/extractor/twentytwotracks.pyc \
    youtube-dl/youtube_dl/extractor/twitch.pyc \
    youtube-dl/youtube_dl/extractor/twitter.pyc \
    youtube-dl/youtube_dl/extractor/udemy.pyc \
    youtube-dl/youtube_dl/extractor/udn.pyc \
    youtube-dl/youtube_dl/extractor/uktvplay.pyc \
    youtube-dl/youtube_dl/extractor/unistra.pyc \
    youtube-dl/youtube_dl/extractor/uol.pyc \
    youtube-dl/youtube_dl/extractor/uplynk.pyc \
    youtube-dl/youtube_dl/extractor/urort.pyc \
    youtube-dl/youtube_dl/extractor/urplay.pyc \
    youtube-dl/youtube_dl/extractor/usanetwork.pyc \
    youtube-dl/youtube_dl/extractor/usatoday.pyc \
    youtube-dl/youtube_dl/extractor/ustream.pyc \
    youtube-dl/youtube_dl/extractor/ustudio.pyc \
    youtube-dl/youtube_dl/extractor/varzesh3.pyc \
    youtube-dl/youtube_dl/extractor/vbox7.pyc \
    youtube-dl/youtube_dl/extractor/veehd.pyc \
    youtube-dl/youtube_dl/extractor/veoh.pyc \
    youtube-dl/youtube_dl/extractor/vessel.pyc \
    youtube-dl/youtube_dl/extractor/vesti.pyc \
    youtube-dl/youtube_dl/extractor/vevo.pyc \
    youtube-dl/youtube_dl/extractor/vgtv.pyc \
    youtube-dl/youtube_dl/extractor/vh1.pyc \
    youtube-dl/youtube_dl/extractor/vice.pyc \
    youtube-dl/youtube_dl/extractor/viceland.pyc \
    youtube-dl/youtube_dl/extractor/vidbit.pyc \
    youtube-dl/youtube_dl/extractor/viddler.pyc \
    youtube-dl/youtube_dl/extractor/videa.pyc \
    youtube-dl/youtube_dl/extractor/videodetective.pyc \
    youtube-dl/youtube_dl/extractor/videofyme.pyc \
    youtube-dl/youtube_dl/extractor/videomega.pyc \
    youtube-dl/youtube_dl/extractor/videomore.pyc \
    youtube-dl/youtube_dl/extractor/videopremium.pyc \
    youtube-dl/youtube_dl/extractor/videopress.pyc \
    youtube-dl/youtube_dl/extractor/vidio.pyc \
    youtube-dl/youtube_dl/extractor/vidme.pyc \
    youtube-dl/youtube_dl/extractor/vidzi.pyc \
    youtube-dl/youtube_dl/extractor/vier.pyc \
    youtube-dl/youtube_dl/extractor/viewlift.pyc \
    youtube-dl/youtube_dl/extractor/viewster.pyc \
    youtube-dl/youtube_dl/extractor/viidea.pyc \
    youtube-dl/youtube_dl/extractor/viki.pyc \
    youtube-dl/youtube_dl/extractor/vimeo.pyc \
    youtube-dl/youtube_dl/extractor/vimple.pyc \
    youtube-dl/youtube_dl/extractor/vine.pyc \
    youtube-dl/youtube_dl/extractor/viu.pyc \
    youtube-dl/youtube_dl/extractor/vk.pyc \
    youtube-dl/youtube_dl/extractor/vlive.pyc \
    youtube-dl/youtube_dl/extractor/vodlocker.pyc \
    youtube-dl/youtube_dl/extractor/vodplatform.pyc \
    youtube-dl/youtube_dl/extractor/voicerepublic.pyc \
    youtube-dl/youtube_dl/extractor/voxmedia.pyc \
    youtube-dl/youtube_dl/extractor/vporn.pyc \
    youtube-dl/youtube_dl/extractor/vrt.pyc \
    youtube-dl/youtube_dl/extractor/vube.pyc \
    youtube-dl/youtube_dl/extractor/vuclip.pyc \
    youtube-dl/youtube_dl/extractor/vvvvid.pyc \
    youtube-dl/youtube_dl/extractor/vyborymos.pyc \
    youtube-dl/youtube_dl/extractor/vzaar.pyc \
    youtube-dl/youtube_dl/extractor/walla.pyc \
    youtube-dl/youtube_dl/extractor/washingtonpost.pyc \
    youtube-dl/youtube_dl/extractor/wat.pyc \
    youtube-dl/youtube_dl/extractor/watchindianporn.pyc \
    youtube-dl/youtube_dl/extractor/wdr.pyc \
    youtube-dl/youtube_dl/extractor/webcaster.pyc \
    youtube-dl/youtube_dl/extractor/webofstories.pyc \
    youtube-dl/youtube_dl/extractor/weiqitv.pyc \
    youtube-dl/youtube_dl/extractor/wimp.pyc \
    youtube-dl/youtube_dl/extractor/wistia.pyc \
    youtube-dl/youtube_dl/extractor/worldstarhiphop.pyc \
    youtube-dl/youtube_dl/extractor/wrzuta.pyc \
    youtube-dl/youtube_dl/extractor/wsj.pyc \
    youtube-dl/youtube_dl/extractor/xbef.pyc \
    youtube-dl/youtube_dl/extractor/xboxclips.pyc \
    youtube-dl/youtube_dl/extractor/xfileshare.pyc \
    youtube-dl/youtube_dl/extractor/xhamster.pyc \
    youtube-dl/youtube_dl/extractor/xiami.pyc \
    youtube-dl/youtube_dl/extractor/xminus.pyc \
    youtube-dl/youtube_dl/extractor/xnxx.pyc \
    youtube-dl/youtube_dl/extractor/xstream.pyc \
    youtube-dl/youtube_dl/extractor/xtube.pyc \
    youtube-dl/youtube_dl/extractor/xuite.pyc \
    youtube-dl/youtube_dl/extractor/xvideos.pyc \
    youtube-dl/youtube_dl/extractor/xxxymovies.pyc \
    youtube-dl/youtube_dl/extractor/yahoo.pyc \
    youtube-dl/youtube_dl/extractor/yam.pyc \
    youtube-dl/youtube_dl/extractor/yandexmusic.pyc \
    youtube-dl/youtube_dl/extractor/yesjapan.pyc \
    youtube-dl/youtube_dl/extractor/yinyuetai.pyc \
    youtube-dl/youtube_dl/extractor/ynet.pyc \
    youtube-dl/youtube_dl/extractor/youjizz.pyc \
    youtube-dl/youtube_dl/extractor/youku.pyc \
    youtube-dl/youtube_dl/extractor/youporn.pyc \
    youtube-dl/youtube_dl/extractor/yourupload.pyc \
    youtube-dl/youtube_dl/extractor/youtube.pyc \
    youtube-dl/youtube_dl/extractor/zapiks.pyc \
    youtube-dl/youtube_dl/extractor/zdf.pyc \
    youtube-dl/youtube_dl/extractor/zingmp3.pyc \
    youtube-dl/youtube_dl/postprocessor/__init__.pyc \
    youtube-dl/youtube_dl/postprocessor/common.pyc \
    youtube-dl/youtube_dl/postprocessor/embedthumbnail.pyc \
    youtube-dl/youtube_dl/postprocessor/execafterdownload.pyc \
    youtube-dl/youtube_dl/postprocessor/ffmpeg.pyc \
    youtube-dl/youtube_dl/postprocessor/metadatafromtitle.pyc \
    youtube-dl/youtube_dl/postprocessor/xattrpp.pyc \
    youtube-dl/youtube_dl/__init__.pyc \
    youtube-dl/youtube_dl/aes.pyc \
    youtube-dl/youtube_dl/cache.pyc \
    youtube-dl/youtube_dl/compat.pyc \
    youtube-dl/youtube_dl/jsinterp.pyc \
    youtube-dl/youtube_dl/options.pyc \
    youtube-dl/youtube_dl/socks.pyc \
    youtube-dl/youtube_dl/swfinterp.pyc \
    youtube-dl/youtube_dl/update.pyc \
    youtube-dl/youtube_dl/utils.pyc \
    youtube-dl/youtube_dl/version.pyc \
    youtube-dl/youtube_dl/YoutubeDL.pyc \
    youtube-dl/devscripts/posix-locale.sh \
    youtube-dl/devscripts/release.sh \
    youtube-dl/devscripts/run_tests.sh \
    youtube-dl/devscripts/wine-py2exe.sh \
    youtube-dl/test/testcert.pem \
    youtube-dl/devscripts/bash-completion.in \
    youtube-dl/devscripts/fish-completion.in \
    youtube-dl/devscripts/zsh-completion.in \
    youtube-dl/docs/index.rst \
    youtube-dl/docs/module_guide.rst \
    youtube-dl/LICENSE \
    youtube-dl/MANIFEST.in \
    youtube-dl/README.txt \
    youtube-dl/youtube-dl.1 \
    youtube-dl/youtube-dl.bash-completion \
    youtube-dl/youtube-dl.fish \
    youtube-dl/youtube-dl.zsh \
    youtube-dl/ChangeLog \
    youtube-dl/docs/supportedsites.md \
    youtube-dl/README.md \
    youtube-dl/devscripts/SizeOfImage.patch \
    youtube-dl/devscripts/SizeOfImage_w.patch \
    youtube-dl/bin/youtube-dl \
    youtube-dl/devscripts/gh-pages/add-version.py \
    youtube-dl/devscripts/gh-pages/generate-download.py \
    youtube-dl/devscripts/gh-pages/sign-versions.py \
    youtube-dl/devscripts/gh-pages/update-copyright.py \
    youtube-dl/devscripts/gh-pages/update-feed.py \
    youtube-dl/devscripts/gh-pages/update-sites.py \
    youtube-dl/devscripts/bash-completion.py \
    youtube-dl/devscripts/buildserver.py \
    youtube-dl/devscripts/check-porn.py \
    youtube-dl/devscripts/create-github-release.py \
    youtube-dl/devscripts/fish-completion.py \
    youtube-dl/devscripts/generate_aes_testdata.py \
    youtube-dl/devscripts/lazy_load_template.py \
    youtube-dl/devscripts/make_contributing.py \
    youtube-dl/devscripts/make_issue_template.py \
    youtube-dl/devscripts/make_lazy_extractors.py \
    youtube-dl/devscripts/make_readme.py \
    youtube-dl/devscripts/make_supportedsites.py \
    youtube-dl/devscripts/prepare_manpage.py \
    youtube-dl/devscripts/show-downloads-statistics.py \
    youtube-dl/devscripts/zsh-completion.py \
    youtube-dl/docs/conf.py \
    youtube-dl/test/__init__.py \
    youtube-dl/test/helper.py \
    youtube-dl/test/test_aes.py \
    youtube-dl/test/test_age_restriction.py \
    youtube-dl/test/test_all_urls.py \
    youtube-dl/test/test_cache.py \
    youtube-dl/test/test_compat.py \
    youtube-dl/test/test_download.py \
    youtube-dl/test/test_execution.py \
    youtube-dl/test/test_http.py \
    youtube-dl/test/test_InfoExtractor.py \
    youtube-dl/test/test_iqiyi_sdk_interpreter.py \
    youtube-dl/test/test_jsinterp.py \
    youtube-dl/test/test_netrc.py \
    youtube-dl/test/test_postprocessors.py \
    youtube-dl/test/test_socks.py \
    youtube-dl/test/test_subtitles.py \
    youtube-dl/test/test_swfinterp.py \
    youtube-dl/test/test_unicode_literals.py \
    youtube-dl/test/test_update.py \
    youtube-dl/test/test_utils.py \
    youtube-dl/test/test_verbose_output.py \
    youtube-dl/test/test_write_annotations.py \
    youtube-dl/test/test_youtube_lists.py \
    youtube-dl/test/test_youtube_signature.py \
    youtube-dl/test/test_YoutubeDL.py \
    youtube-dl/youtube_dl/downloader/__init__.py \
    youtube-dl/youtube_dl/downloader/common.py \
    youtube-dl/youtube_dl/downloader/dash.py \
    youtube-dl/youtube_dl/downloader/external.py \
    youtube-dl/youtube_dl/downloader/f4m.py \
    youtube-dl/youtube_dl/downloader/fragment.py \
    youtube-dl/youtube_dl/downloader/hls.py \
    youtube-dl/youtube_dl/downloader/http.py \
    youtube-dl/youtube_dl/downloader/ism.py \
    youtube-dl/youtube_dl/downloader/rtmp.py \
    youtube-dl/youtube_dl/downloader/rtsp.py \
    youtube-dl/youtube_dl/extractor/__init__.py \
    youtube-dl/youtube_dl/extractor/abc.py \
    youtube-dl/youtube_dl/extractor/abcnews.py \
    youtube-dl/youtube_dl/extractor/abcotvs.py \
    youtube-dl/youtube_dl/extractor/academicearth.py \
    youtube-dl/youtube_dl/extractor/acast.py \
    youtube-dl/youtube_dl/extractor/addanime.py \
    youtube-dl/youtube_dl/extractor/adobepass.py \
    youtube-dl/youtube_dl/extractor/adobetv.py \
    youtube-dl/youtube_dl/extractor/adultswim.py \
    youtube-dl/youtube_dl/extractor/aenetworks.py \
    youtube-dl/youtube_dl/extractor/afreecatv.py \
    youtube-dl/youtube_dl/extractor/airmozilla.py \
    youtube-dl/youtube_dl/extractor/aljazeera.py \
    youtube-dl/youtube_dl/extractor/allocine.py \
    youtube-dl/youtube_dl/extractor/alphaporno.py \
    youtube-dl/youtube_dl/extractor/amcnetworks.py \
    youtube-dl/youtube_dl/extractor/amp.py \
    youtube-dl/youtube_dl/extractor/animeondemand.py \
    youtube-dl/youtube_dl/extractor/anitube.py \
    youtube-dl/youtube_dl/extractor/anvato.py \
    youtube-dl/youtube_dl/extractor/anysex.py \
    youtube-dl/youtube_dl/extractor/aol.py \
    youtube-dl/youtube_dl/extractor/aparat.py \
    youtube-dl/youtube_dl/extractor/appleconnect.py \
    youtube-dl/youtube_dl/extractor/appletrailers.py \
    youtube-dl/youtube_dl/extractor/archiveorg.py \
    youtube-dl/youtube_dl/extractor/ard.py \
    youtube-dl/youtube_dl/extractor/arkena.py \
    youtube-dl/youtube_dl/extractor/arte.py \
    youtube-dl/youtube_dl/extractor/atresplayer.py \
    youtube-dl/youtube_dl/extractor/atttechchannel.py \
    youtube-dl/youtube_dl/extractor/audimedia.py \
    youtube-dl/youtube_dl/extractor/audioboom.py \
    youtube-dl/youtube_dl/extractor/audiomack.py \
    youtube-dl/youtube_dl/extractor/awaan.py \
    youtube-dl/youtube_dl/extractor/azmedien.py \
    youtube-dl/youtube_dl/extractor/azubu.py \
    youtube-dl/youtube_dl/extractor/baidu.py \
    youtube-dl/youtube_dl/extractor/bambuser.py \
    youtube-dl/youtube_dl/extractor/bandcamp.py \
    youtube-dl/youtube_dl/extractor/bbc.py \
    youtube-dl/youtube_dl/extractor/beampro.py \
    youtube-dl/youtube_dl/extractor/beatport.py \
    youtube-dl/youtube_dl/extractor/beeg.py \
    youtube-dl/youtube_dl/extractor/behindkink.py \
    youtube-dl/youtube_dl/extractor/bellmedia.py \
    youtube-dl/youtube_dl/extractor/bet.py \
    youtube-dl/youtube_dl/extractor/bigflix.py \
    youtube-dl/youtube_dl/extractor/bild.py \
    youtube-dl/youtube_dl/extractor/bilibili.py \
    youtube-dl/youtube_dl/extractor/biobiochiletv.py \
    youtube-dl/youtube_dl/extractor/biqle.py \
    youtube-dl/youtube_dl/extractor/bleacherreport.py \
    youtube-dl/youtube_dl/extractor/blinkx.py \
    youtube-dl/youtube_dl/extractor/bloomberg.py \
    youtube-dl/youtube_dl/extractor/bokecc.py \
    youtube-dl/youtube_dl/extractor/bpb.py \
    youtube-dl/youtube_dl/extractor/br.py \
    youtube-dl/youtube_dl/extractor/bravotv.py \
    youtube-dl/youtube_dl/extractor/breakcom.py \
    youtube-dl/youtube_dl/extractor/brightcove.py \
    youtube-dl/youtube_dl/extractor/buzzfeed.py \
    youtube-dl/youtube_dl/extractor/byutv.py \
    youtube-dl/youtube_dl/extractor/c56.py \
    youtube-dl/youtube_dl/extractor/camdemy.py \
    youtube-dl/youtube_dl/extractor/camwithher.py \
    youtube-dl/youtube_dl/extractor/canalc2.py \
    youtube-dl/youtube_dl/extractor/canalplus.py \
    youtube-dl/youtube_dl/extractor/canvas.py \
    youtube-dl/youtube_dl/extractor/carambatv.py \
    youtube-dl/youtube_dl/extractor/cartoonnetwork.py \
    youtube-dl/youtube_dl/extractor/cbc.py \
    youtube-dl/youtube_dl/extractor/cbs.py \
    youtube-dl/youtube_dl/extractor/cbsinteractive.py \
    youtube-dl/youtube_dl/extractor/cbslocal.py \
    youtube-dl/youtube_dl/extractor/cbsnews.py \
    youtube-dl/youtube_dl/extractor/cbssports.py \
    youtube-dl/youtube_dl/extractor/ccc.py \
    youtube-dl/youtube_dl/extractor/ccma.py \
    youtube-dl/youtube_dl/extractor/cctv.py \
    youtube-dl/youtube_dl/extractor/cda.py \
    youtube-dl/youtube_dl/extractor/ceskatelevize.py \
    youtube-dl/youtube_dl/extractor/channel9.py \
    youtube-dl/youtube_dl/extractor/charlierose.py \
    youtube-dl/youtube_dl/extractor/chaturbate.py \
    youtube-dl/youtube_dl/extractor/chilloutzone.py \
    youtube-dl/youtube_dl/extractor/chirbit.py \
    youtube-dl/youtube_dl/extractor/cinchcast.py \
    youtube-dl/youtube_dl/extractor/clipfish.py \
    youtube-dl/youtube_dl/extractor/cliphunter.py \
    youtube-dl/youtube_dl/extractor/cliprs.py \
    youtube-dl/youtube_dl/extractor/clipsyndicate.py \
    youtube-dl/youtube_dl/extractor/closertotruth.py \
    youtube-dl/youtube_dl/extractor/cloudy.py \
    youtube-dl/youtube_dl/extractor/clubic.py \
    youtube-dl/youtube_dl/extractor/clyp.py \
    youtube-dl/youtube_dl/extractor/cmt.py \
    youtube-dl/youtube_dl/extractor/cnbc.py \
    youtube-dl/youtube_dl/extractor/cnn.py \
    youtube-dl/youtube_dl/extractor/collegerama.py \
    youtube-dl/youtube_dl/extractor/comcarcoff.py \
    youtube-dl/youtube_dl/extractor/comedycentral.py \
    youtube-dl/youtube_dl/extractor/common.py \
    youtube-dl/youtube_dl/extractor/commonmistakes.py \
    youtube-dl/youtube_dl/extractor/commonprotocols.py \
    youtube-dl/youtube_dl/extractor/condenast.py \
    youtube-dl/youtube_dl/extractor/corus.py \
    youtube-dl/youtube_dl/extractor/coub.py \
    youtube-dl/youtube_dl/extractor/cracked.py \
    youtube-dl/youtube_dl/extractor/crackle.py \
    youtube-dl/youtube_dl/extractor/criterion.py \
    youtube-dl/youtube_dl/extractor/crooksandliars.py \
    youtube-dl/youtube_dl/extractor/crunchyroll.py \
    youtube-dl/youtube_dl/extractor/cspan.py \
    youtube-dl/youtube_dl/extractor/ctsnews.py \
    youtube-dl/youtube_dl/extractor/ctvnews.py \
    youtube-dl/youtube_dl/extractor/cultureunplugged.py \
    youtube-dl/youtube_dl/extractor/curiositystream.py \
    youtube-dl/youtube_dl/extractor/cwtv.py \
    youtube-dl/youtube_dl/extractor/dailymail.py \
    youtube-dl/youtube_dl/extractor/dailymotion.py \
    youtube-dl/youtube_dl/extractor/daum.py \
    youtube-dl/youtube_dl/extractor/dbtv.py \
    youtube-dl/youtube_dl/extractor/dctp.py \
    youtube-dl/youtube_dl/extractor/deezer.py \
    youtube-dl/youtube_dl/extractor/defense.py \
    youtube-dl/youtube_dl/extractor/democracynow.py \
    youtube-dl/youtube_dl/extractor/dfb.py \
    youtube-dl/youtube_dl/extractor/dhm.py \
    youtube-dl/youtube_dl/extractor/digiteka.py \
    youtube-dl/youtube_dl/extractor/discovery.py \
    youtube-dl/youtube_dl/extractor/discoverygo.py \
    youtube-dl/youtube_dl/extractor/disney.py \
    youtube-dl/youtube_dl/extractor/dispeak.py \
    youtube-dl/youtube_dl/extractor/dotsub.py \
    youtube-dl/youtube_dl/extractor/douyutv.py \
    youtube-dl/youtube_dl/extractor/dplay.py \
    youtube-dl/youtube_dl/extractor/dramafever.py \
    youtube-dl/youtube_dl/extractor/drbonanza.py \
    youtube-dl/youtube_dl/extractor/dreisat.py \
    youtube-dl/youtube_dl/extractor/dropbox.py \
    youtube-dl/youtube_dl/extractor/drtuber.py \
    youtube-dl/youtube_dl/extractor/drtv.py \
    youtube-dl/youtube_dl/extractor/dumpert.py \
    youtube-dl/youtube_dl/extractor/dvtv.py \
    youtube-dl/youtube_dl/extractor/dw.py \
    youtube-dl/youtube_dl/extractor/eagleplatform.py \
    youtube-dl/youtube_dl/extractor/ebaumsworld.py \
    youtube-dl/youtube_dl/extractor/echomsk.py \
    youtube-dl/youtube_dl/extractor/egghead.py \
    youtube-dl/youtube_dl/extractor/ehow.py \
    youtube-dl/youtube_dl/extractor/eighttracks.py \
    youtube-dl/youtube_dl/extractor/einthusan.py \
    youtube-dl/youtube_dl/extractor/eitb.py \
    youtube-dl/youtube_dl/extractor/ellentv.py \
    youtube-dl/youtube_dl/extractor/elpais.py \
    youtube-dl/youtube_dl/extractor/embedly.py \
    youtube-dl/youtube_dl/extractor/engadget.py \
    youtube-dl/youtube_dl/extractor/eporner.py \
    youtube-dl/youtube_dl/extractor/eroprofile.py \
    youtube-dl/youtube_dl/extractor/escapist.py \
    youtube-dl/youtube_dl/extractor/espn.py \
    youtube-dl/youtube_dl/extractor/esri.py \
    youtube-dl/youtube_dl/extractor/europa.py \
    youtube-dl/youtube_dl/extractor/everyonesmixtape.py \
    youtube-dl/youtube_dl/extractor/expotv.py \
    youtube-dl/youtube_dl/extractor/extractors.py \
    youtube-dl/youtube_dl/extractor/extremetube.py \
    youtube-dl/youtube_dl/extractor/eyedotv.py \
    youtube-dl/youtube_dl/extractor/facebook.py \
    youtube-dl/youtube_dl/extractor/faz.py \
    youtube-dl/youtube_dl/extractor/fc2.py \
    youtube-dl/youtube_dl/extractor/fczenit.py \
    youtube-dl/youtube_dl/extractor/filmon.py \
    youtube-dl/youtube_dl/extractor/firstpost.py \
    youtube-dl/youtube_dl/extractor/firsttv.py \
    youtube-dl/youtube_dl/extractor/fivemin.py \
    youtube-dl/youtube_dl/extractor/fivetv.py \
    youtube-dl/youtube_dl/extractor/fktv.py \
    youtube-dl/youtube_dl/extractor/flickr.py \
    youtube-dl/youtube_dl/extractor/flipagram.py \
    youtube-dl/youtube_dl/extractor/folketinget.py \
    youtube-dl/youtube_dl/extractor/footyroom.py \
    youtube-dl/youtube_dl/extractor/formula1.py \
    youtube-dl/youtube_dl/extractor/fourtube.py \
    youtube-dl/youtube_dl/extractor/fox.py \
    youtube-dl/youtube_dl/extractor/fox9.py \
    youtube-dl/youtube_dl/extractor/foxgay.py \
    youtube-dl/youtube_dl/extractor/foxnews.py \
    youtube-dl/youtube_dl/extractor/foxsports.py \
    youtube-dl/youtube_dl/extractor/franceculture.py \
    youtube-dl/youtube_dl/extractor/franceinter.py \
    youtube-dl/youtube_dl/extractor/francetv.py \
    youtube-dl/youtube_dl/extractor/freesound.py \
    youtube-dl/youtube_dl/extractor/freespeech.py \
    youtube-dl/youtube_dl/extractor/funimation.py \
    youtube-dl/youtube_dl/extractor/funnyordie.py \
    youtube-dl/youtube_dl/extractor/fusion.py \
    youtube-dl/youtube_dl/extractor/fxnetworks.py \
    youtube-dl/youtube_dl/extractor/gameinformer.py \
    youtube-dl/youtube_dl/extractor/gameone.py \
    youtube-dl/youtube_dl/extractor/gamersyde.py \
    youtube-dl/youtube_dl/extractor/gamespot.py \
    youtube-dl/youtube_dl/extractor/gamestar.py \
    youtube-dl/youtube_dl/extractor/gaskrank.py \
    youtube-dl/youtube_dl/extractor/gazeta.py \
    youtube-dl/youtube_dl/extractor/gdcvault.py \
    youtube-dl/youtube_dl/extractor/generic.py \
    youtube-dl/youtube_dl/extractor/gfycat.py \
    youtube-dl/youtube_dl/extractor/giantbomb.py \
    youtube-dl/youtube_dl/extractor/giga.py \
    youtube-dl/youtube_dl/extractor/glide.py \
    youtube-dl/youtube_dl/extractor/globo.py \
    youtube-dl/youtube_dl/extractor/go.py \
    youtube-dl/youtube_dl/extractor/godtube.py \
    youtube-dl/youtube_dl/extractor/godtv.py \
    youtube-dl/youtube_dl/extractor/golem.py \
    youtube-dl/youtube_dl/extractor/googledrive.py \
    youtube-dl/youtube_dl/extractor/googleplus.py \
    youtube-dl/youtube_dl/extractor/googlesearch.py \
    youtube-dl/youtube_dl/extractor/goshgay.py \
    youtube-dl/youtube_dl/extractor/gputechconf.py \
    youtube-dl/youtube_dl/extractor/groupon.py \
    youtube-dl/youtube_dl/extractor/hark.py \
    youtube-dl/youtube_dl/extractor/hbo.py \
    youtube-dl/youtube_dl/extractor/hearthisat.py \
    youtube-dl/youtube_dl/extractor/heise.py \
    youtube-dl/youtube_dl/extractor/hellporno.py \
    youtube-dl/youtube_dl/extractor/helsinki.py \
    youtube-dl/youtube_dl/extractor/hentaistigma.py \
    youtube-dl/youtube_dl/extractor/hgtv.py \
    youtube-dl/youtube_dl/extractor/historicfilms.py \
    youtube-dl/youtube_dl/extractor/hitbox.py \
    youtube-dl/youtube_dl/extractor/hitrecord.py \
    youtube-dl/youtube_dl/extractor/hornbunny.py \
    youtube-dl/youtube_dl/extractor/hotnewhiphop.py \
    youtube-dl/youtube_dl/extractor/hotstar.py \
    youtube-dl/youtube_dl/extractor/howcast.py \
    youtube-dl/youtube_dl/extractor/howstuffworks.py \
    youtube-dl/youtube_dl/extractor/hrti.py \
    youtube-dl/youtube_dl/extractor/huajiao.py \
    youtube-dl/youtube_dl/extractor/huffpost.py \
    youtube-dl/youtube_dl/extractor/hypem.py \
    youtube-dl/youtube_dl/extractor/iconosquare.py \
    youtube-dl/youtube_dl/extractor/ign.py \
    youtube-dl/youtube_dl/extractor/imdb.py \
    youtube-dl/youtube_dl/extractor/imgur.py \
    youtube-dl/youtube_dl/extractor/ina.py \
    youtube-dl/youtube_dl/extractor/inc.py \
    youtube-dl/youtube_dl/extractor/indavideo.py \
    youtube-dl/youtube_dl/extractor/infoq.py \
    youtube-dl/youtube_dl/extractor/instagram.py \
    youtube-dl/youtube_dl/extractor/internetvideoarchive.py \
    youtube-dl/youtube_dl/extractor/iprima.py \
    youtube-dl/youtube_dl/extractor/iqiyi.py \
    youtube-dl/youtube_dl/extractor/ir90tv.py \
    youtube-dl/youtube_dl/extractor/itv.py \
    youtube-dl/youtube_dl/extractor/ivi.py \
    youtube-dl/youtube_dl/extractor/ivideon.py \
    youtube-dl/youtube_dl/extractor/iwara.py \
    youtube-dl/youtube_dl/extractor/izlesene.py \
    youtube-dl/youtube_dl/extractor/jamendo.py \
    youtube-dl/youtube_dl/extractor/jeuxvideo.py \
    youtube-dl/youtube_dl/extractor/jove.py \
    youtube-dl/youtube_dl/extractor/jpopsukitv.py \
    youtube-dl/youtube_dl/extractor/jwplatform.py \
    youtube-dl/youtube_dl/extractor/kaltura.py \
    youtube-dl/youtube_dl/extractor/kamcord.py \
    youtube-dl/youtube_dl/extractor/kanalplay.py \
    youtube-dl/youtube_dl/extractor/kankan.py \
    youtube-dl/youtube_dl/extractor/karaoketv.py \
    youtube-dl/youtube_dl/extractor/karrierevideos.py \
    youtube-dl/youtube_dl/extractor/keek.py \
    youtube-dl/youtube_dl/extractor/keezmovies.py \
    youtube-dl/youtube_dl/extractor/ketnet.py \
    youtube-dl/youtube_dl/extractor/khanacademy.py \
    youtube-dl/youtube_dl/extractor/kickstarter.py \
    youtube-dl/youtube_dl/extractor/konserthusetplay.py \
    youtube-dl/youtube_dl/extractor/kontrtube.py \
    youtube-dl/youtube_dl/extractor/krasview.py \
    youtube-dl/youtube_dl/extractor/ku6.py \
    youtube-dl/youtube_dl/extractor/kusi.py \
    youtube-dl/youtube_dl/extractor/kuwo.py \
    youtube-dl/youtube_dl/extractor/la7.py \
    youtube-dl/youtube_dl/extractor/laola1tv.py \
    youtube-dl/youtube_dl/extractor/lci.py \
    youtube-dl/youtube_dl/extractor/lcp.py \
    youtube-dl/youtube_dl/extractor/learnr.py \
    youtube-dl/youtube_dl/extractor/lecture2go.py \
    youtube-dl/youtube_dl/extractor/leeco.py \
    youtube-dl/youtube_dl/extractor/lego.py \
    youtube-dl/youtube_dl/extractor/lemonde.py \
    youtube-dl/youtube_dl/extractor/libraryofcongress.py \
    youtube-dl/youtube_dl/extractor/libsyn.py \
    youtube-dl/youtube_dl/extractor/lifenews.py \
    youtube-dl/youtube_dl/extractor/limelight.py \
    youtube-dl/youtube_dl/extractor/litv.py \
    youtube-dl/youtube_dl/extractor/liveleak.py \
    youtube-dl/youtube_dl/extractor/livestream.py \
    youtube-dl/youtube_dl/extractor/lnkgo.py \
    youtube-dl/youtube_dl/extractor/localnews8.py \
    youtube-dl/youtube_dl/extractor/lovehomeporn.py \
    youtube-dl/youtube_dl/extractor/lrt.py \
    youtube-dl/youtube_dl/extractor/lynda.py \
    youtube-dl/youtube_dl/extractor/m6.py \
    youtube-dl/youtube_dl/extractor/macgamestore.py \
    youtube-dl/youtube_dl/extractor/mailru.py \
    youtube-dl/youtube_dl/extractor/makerschannel.py \
    youtube-dl/youtube_dl/extractor/makertv.py \
    youtube-dl/youtube_dl/extractor/mangomolo.py \
    youtube-dl/youtube_dl/extractor/matchtv.py \
    youtube-dl/youtube_dl/extractor/mdr.py \
    youtube-dl/youtube_dl/extractor/meipai.py \
    youtube-dl/youtube_dl/extractor/melonvod.py \
    youtube-dl/youtube_dl/extractor/meta.py \
    youtube-dl/youtube_dl/extractor/metacafe.py \
    youtube-dl/youtube_dl/extractor/metacritic.py \
    youtube-dl/youtube_dl/extractor/mgoon.py \
    youtube-dl/youtube_dl/extractor/mgtv.py \
    youtube-dl/youtube_dl/extractor/miaopai.py \
    youtube-dl/youtube_dl/extractor/microsoftvirtualacademy.py \
    youtube-dl/youtube_dl/extractor/minhateca.py \
    youtube-dl/youtube_dl/extractor/ministrygrid.py \
    youtube-dl/youtube_dl/extractor/minoto.py \
    youtube-dl/youtube_dl/extractor/miomio.py \
    youtube-dl/youtube_dl/extractor/mit.py \
    youtube-dl/youtube_dl/extractor/mitele.py \
    youtube-dl/youtube_dl/extractor/mixcloud.py \
    youtube-dl/youtube_dl/extractor/mlb.py \
    youtube-dl/youtube_dl/extractor/mnet.py \
    youtube-dl/youtube_dl/extractor/moevideo.py \
    youtube-dl/youtube_dl/extractor/mofosex.py \
    youtube-dl/youtube_dl/extractor/mojvideo.py \
    youtube-dl/youtube_dl/extractor/moniker.py \
    youtube-dl/youtube_dl/extractor/morningstar.py \
    youtube-dl/youtube_dl/extractor/motherless.py \
    youtube-dl/youtube_dl/extractor/motorsport.py \
    youtube-dl/youtube_dl/extractor/movieclips.py \
    youtube-dl/youtube_dl/extractor/moviezine.py \
    youtube-dl/youtube_dl/extractor/movingimage.py \
    youtube-dl/youtube_dl/extractor/mpora.py \
    youtube-dl/youtube_dl/extractor/msn.py \
    youtube-dl/youtube_dl/extractor/mtv.py \
    youtube-dl/youtube_dl/extractor/muenchentv.py \
    youtube-dl/youtube_dl/extractor/musicplayon.py \
    youtube-dl/youtube_dl/extractor/mwave.py \
    youtube-dl/youtube_dl/extractor/myspace.py \
    youtube-dl/youtube_dl/extractor/myspass.py \
    youtube-dl/youtube_dl/extractor/myvi.py \
    youtube-dl/youtube_dl/extractor/myvideo.py \
    youtube-dl/youtube_dl/extractor/myvidster.py \
    youtube-dl/youtube_dl/extractor/nationalgeographic.py \
    youtube-dl/youtube_dl/extractor/naver.py \
    youtube-dl/youtube_dl/extractor/nba.py \
    youtube-dl/youtube_dl/extractor/nbc.py \
    youtube-dl/youtube_dl/extractor/ndr.py \
    youtube-dl/youtube_dl/extractor/ndtv.py \
    youtube-dl/youtube_dl/extractor/nerdcubed.py \
    youtube-dl/youtube_dl/extractor/neteasemusic.py \
    youtube-dl/youtube_dl/extractor/netzkino.py \
    youtube-dl/youtube_dl/extractor/newgrounds.py \
    youtube-dl/youtube_dl/extractor/newstube.py \
    youtube-dl/youtube_dl/extractor/nextmedia.py \
    youtube-dl/youtube_dl/extractor/nfb.py \
    youtube-dl/youtube_dl/extractor/nfl.py \
    youtube-dl/youtube_dl/extractor/nhk.py \
    youtube-dl/youtube_dl/extractor/nhl.py \
    youtube-dl/youtube_dl/extractor/nick.py \
    youtube-dl/youtube_dl/extractor/niconico.py \
    youtube-dl/youtube_dl/extractor/ninecninemedia.py \
    youtube-dl/youtube_dl/extractor/ninegag.py \
    youtube-dl/youtube_dl/extractor/ninenow.py \
    youtube-dl/youtube_dl/extractor/nintendo.py \
    youtube-dl/youtube_dl/extractor/nobelprize.py \
    youtube-dl/youtube_dl/extractor/noco.py \
    youtube-dl/youtube_dl/extractor/normalboots.py \
    youtube-dl/youtube_dl/extractor/nosvideo.py \
    youtube-dl/youtube_dl/extractor/nova.py \
    youtube-dl/youtube_dl/extractor/novamov.py \
    youtube-dl/youtube_dl/extractor/nowness.py \
    youtube-dl/youtube_dl/extractor/nowtv.py \
    youtube-dl/youtube_dl/extractor/noz.py \
    youtube-dl/youtube_dl/extractor/npo.py \
    youtube-dl/youtube_dl/extractor/npr.py \
    youtube-dl/youtube_dl/extractor/nrk.py \
    youtube-dl/youtube_dl/extractor/ntvde.py \
    youtube-dl/youtube_dl/extractor/ntvru.py \
    youtube-dl/youtube_dl/extractor/nuevo.py \
    youtube-dl/youtube_dl/extractor/nuvid.py \
    youtube-dl/youtube_dl/extractor/nytimes.py \
    youtube-dl/youtube_dl/extractor/nzz.py \
    youtube-dl/youtube_dl/extractor/odatv.py \
    youtube-dl/youtube_dl/extractor/odnoklassniki.py \
    youtube-dl/youtube_dl/extractor/oktoberfesttv.py \
    youtube-dl/youtube_dl/extractor/once.py \
    youtube-dl/youtube_dl/extractor/ondemandkorea.py \
    youtube-dl/youtube_dl/extractor/onet.py \
    youtube-dl/youtube_dl/extractor/onionstudios.py \
    youtube-dl/youtube_dl/extractor/ooyala.py \
    youtube-dl/youtube_dl/extractor/openload.py \
    youtube-dl/youtube_dl/extractor/ora.py \
    youtube-dl/youtube_dl/extractor/orf.py \
    youtube-dl/youtube_dl/extractor/pandatv.py \
    youtube-dl/youtube_dl/extractor/pandoratv.py \
    youtube-dl/youtube_dl/extractor/parliamentliveuk.py \
    youtube-dl/youtube_dl/extractor/patreon.py \
    youtube-dl/youtube_dl/extractor/pbs.py \
    youtube-dl/youtube_dl/extractor/people.py \
    youtube-dl/youtube_dl/extractor/periscope.py \
    youtube-dl/youtube_dl/extractor/philharmoniedeparis.py \
    youtube-dl/youtube_dl/extractor/phoenix.py \
    youtube-dl/youtube_dl/extractor/photobucket.py \
    youtube-dl/youtube_dl/extractor/piksel.py \
    youtube-dl/youtube_dl/extractor/pinkbike.py \
    youtube-dl/youtube_dl/extractor/pladform.py \
    youtube-dl/youtube_dl/extractor/playfm.py \
    youtube-dl/youtube_dl/extractor/plays.py \
    youtube-dl/youtube_dl/extractor/playtvak.py \
    youtube-dl/youtube_dl/extractor/playvid.py \
    youtube-dl/youtube_dl/extractor/playwire.py \
    youtube-dl/youtube_dl/extractor/pluralsight.py \
    youtube-dl/youtube_dl/extractor/podomatic.py \
    youtube-dl/youtube_dl/extractor/pokemon.py \
    youtube-dl/youtube_dl/extractor/polskieradio.py \
    youtube-dl/youtube_dl/extractor/porn91.py \
    youtube-dl/youtube_dl/extractor/porncom.py \
    youtube-dl/youtube_dl/extractor/pornflip.py \
    youtube-dl/youtube_dl/extractor/pornhd.py \
    youtube-dl/youtube_dl/extractor/pornhub.py \
    youtube-dl/youtube_dl/extractor/pornotube.py \
    youtube-dl/youtube_dl/extractor/pornovoisines.py \
    youtube-dl/youtube_dl/extractor/pornoxo.py \
    youtube-dl/youtube_dl/extractor/presstv.py \
    youtube-dl/youtube_dl/extractor/primesharetv.py \
    youtube-dl/youtube_dl/extractor/promptfile.py \
    youtube-dl/youtube_dl/extractor/prosiebensat1.py \
    youtube-dl/youtube_dl/extractor/puls4.py \
    youtube-dl/youtube_dl/extractor/pyvideo.py \
    youtube-dl/youtube_dl/extractor/qqmusic.py \
    youtube-dl/youtube_dl/extractor/r7.py \
    youtube-dl/youtube_dl/extractor/radiobremen.py \
    youtube-dl/youtube_dl/extractor/radiocanada.py \
    youtube-dl/youtube_dl/extractor/radiode.py \
    youtube-dl/youtube_dl/extractor/radiofrance.py \
    youtube-dl/youtube_dl/extractor/radiojavan.py \
    youtube-dl/youtube_dl/extractor/rai.py \
    youtube-dl/youtube_dl/extractor/rbmaradio.py \
    youtube-dl/youtube_dl/extractor/rds.py \
    youtube-dl/youtube_dl/extractor/redtube.py \
    youtube-dl/youtube_dl/extractor/regiotv.py \
    youtube-dl/youtube_dl/extractor/rentv.py \
    youtube-dl/youtube_dl/extractor/restudy.py \
    youtube-dl/youtube_dl/extractor/reuters.py \
    youtube-dl/youtube_dl/extractor/reverbnation.py \
    youtube-dl/youtube_dl/extractor/revision3.py \
    youtube-dl/youtube_dl/extractor/rice.py \
    youtube-dl/youtube_dl/extractor/ringtv.py \
    youtube-dl/youtube_dl/extractor/rmcdecouverte.py \
    youtube-dl/youtube_dl/extractor/ro220.py \
    youtube-dl/youtube_dl/extractor/rockstargames.py \
    youtube-dl/youtube_dl/extractor/roosterteeth.py \
    youtube-dl/youtube_dl/extractor/rottentomatoes.py \
    youtube-dl/youtube_dl/extractor/roxwel.py \
    youtube-dl/youtube_dl/extractor/rozhlas.py \
    youtube-dl/youtube_dl/extractor/rtbf.py \
    youtube-dl/youtube_dl/extractor/rte.py \
    youtube-dl/youtube_dl/extractor/rtl2.py \
    youtube-dl/youtube_dl/extractor/rtlnl.py \
    youtube-dl/youtube_dl/extractor/rtp.py \
    youtube-dl/youtube_dl/extractor/rts.py \
    youtube-dl/youtube_dl/extractor/rtve.py \
    youtube-dl/youtube_dl/extractor/rtvnh.py \
    youtube-dl/youtube_dl/extractor/rudo.py \
    youtube-dl/youtube_dl/extractor/ruhd.py \
    youtube-dl/youtube_dl/extractor/ruleporn.py \
    youtube-dl/youtube_dl/extractor/rutube.py \
    youtube-dl/youtube_dl/extractor/rutv.py \
    youtube-dl/youtube_dl/extractor/ruutu.py \
    youtube-dl/youtube_dl/extractor/safari.py \
    youtube-dl/youtube_dl/extractor/sandia.py \
    youtube-dl/youtube_dl/extractor/sapo.py \
    youtube-dl/youtube_dl/extractor/savefrom.py \
    youtube-dl/youtube_dl/extractor/sbs.py \
    youtube-dl/youtube_dl/extractor/scivee.py \
    youtube-dl/youtube_dl/extractor/screencast.py \
    youtube-dl/youtube_dl/extractor/screencastomatic.py \
    youtube-dl/youtube_dl/extractor/scrippsnetworks.py \
    youtube-dl/youtube_dl/extractor/seeker.py \
    youtube-dl/youtube_dl/extractor/senateisvp.py \
    youtube-dl/youtube_dl/extractor/sendtonews.py \
    youtube-dl/youtube_dl/extractor/servingsys.py \
    youtube-dl/youtube_dl/extractor/sexu.py \
    youtube-dl/youtube_dl/extractor/shahid.py \
    youtube-dl/youtube_dl/extractor/shared.py \
    youtube-dl/youtube_dl/extractor/showroomlive.py \
    youtube-dl/youtube_dl/extractor/sina.py \
    youtube-dl/youtube_dl/extractor/sixplay.py \
    youtube-dl/youtube_dl/extractor/skynewsarabia.py \
    youtube-dl/youtube_dl/extractor/skysports.py \
    youtube-dl/youtube_dl/extractor/slideshare.py \
    youtube-dl/youtube_dl/extractor/slutload.py \
    youtube-dl/youtube_dl/extractor/smotri.py \
    youtube-dl/youtube_dl/extractor/snotr.py \
    youtube-dl/youtube_dl/extractor/sohu.py \
    youtube-dl/youtube_dl/extractor/sonyliv.py \
    youtube-dl/youtube_dl/extractor/soundcloud.py \
    youtube-dl/youtube_dl/extractor/soundgasm.py \
    youtube-dl/youtube_dl/extractor/southpark.py \
    youtube-dl/youtube_dl/extractor/spankbang.py \
    youtube-dl/youtube_dl/extractor/spankwire.py \
    youtube-dl/youtube_dl/extractor/spiegel.py \
    youtube-dl/youtube_dl/extractor/spiegeltv.py \
    youtube-dl/youtube_dl/extractor/spike.py \
    youtube-dl/youtube_dl/extractor/sport5.py \
    youtube-dl/youtube_dl/extractor/sportbox.py \
    youtube-dl/youtube_dl/extractor/sportdeutschland.py \
    youtube-dl/youtube_dl/extractor/sportschau.py \
    youtube-dl/youtube_dl/extractor/sprout.py \
    youtube-dl/youtube_dl/extractor/srgssr.py \
    youtube-dl/youtube_dl/extractor/srmediathek.py \
    youtube-dl/youtube_dl/extractor/stanfordoc.py \
    youtube-dl/youtube_dl/extractor/steam.py \
    youtube-dl/youtube_dl/extractor/stitcher.py \
    youtube-dl/youtube_dl/extractor/streamable.py \
    youtube-dl/youtube_dl/extractor/streamcloud.py \
    youtube-dl/youtube_dl/extractor/streamcz.py \
    youtube-dl/youtube_dl/extractor/streetvoice.py \
    youtube-dl/youtube_dl/extractor/sunporno.py \
    youtube-dl/youtube_dl/extractor/svt.py \
    youtube-dl/youtube_dl/extractor/swrmediathek.py \
    youtube-dl/youtube_dl/extractor/syfy.py \
    youtube-dl/youtube_dl/extractor/sztvhu.py \
    youtube-dl/youtube_dl/extractor/tagesschau.py \
    youtube-dl/youtube_dl/extractor/tass.py \
    youtube-dl/youtube_dl/extractor/tbs.py \
    youtube-dl/youtube_dl/extractor/tdslifeway.py \
    youtube-dl/youtube_dl/extractor/teachertube.py \
    youtube-dl/youtube_dl/extractor/teachingchannel.py \
    youtube-dl/youtube_dl/extractor/teamcoco.py \
    youtube-dl/youtube_dl/extractor/teamfourstar.py \
    youtube-dl/youtube_dl/extractor/techtalks.py \
    youtube-dl/youtube_dl/extractor/ted.py \
    youtube-dl/youtube_dl/extractor/tele13.py \
    youtube-dl/youtube_dl/extractor/telebruxelles.py \
    youtube-dl/youtube_dl/extractor/telecinco.py \
    youtube-dl/youtube_dl/extractor/telegraaf.py \
    youtube-dl/youtube_dl/extractor/telemb.py \
    youtube-dl/youtube_dl/extractor/telequebec.py \
    youtube-dl/youtube_dl/extractor/teletask.py \
    youtube-dl/youtube_dl/extractor/telewebion.py \
    youtube-dl/youtube_dl/extractor/testurl.py \
    youtube-dl/youtube_dl/extractor/tf1.py \
    youtube-dl/youtube_dl/extractor/tfo.py \
    youtube-dl/youtube_dl/extractor/theintercept.py \
    youtube-dl/youtube_dl/extractor/theplatform.py \
    youtube-dl/youtube_dl/extractor/thescene.py \
    youtube-dl/youtube_dl/extractor/thesixtyone.py \
    youtube-dl/youtube_dl/extractor/thestar.py \
    youtube-dl/youtube_dl/extractor/theweatherchannel.py \
    youtube-dl/youtube_dl/extractor/thisamericanlife.py \
    youtube-dl/youtube_dl/extractor/thisav.py \
    youtube-dl/youtube_dl/extractor/thisoldhouse.py \
    youtube-dl/youtube_dl/extractor/threeqsdn.py \
    youtube-dl/youtube_dl/extractor/tinypic.py \
    youtube-dl/youtube_dl/extractor/tlc.py \
    youtube-dl/youtube_dl/extractor/tmz.py \
    youtube-dl/youtube_dl/extractor/tnaflix.py \
    youtube-dl/youtube_dl/extractor/toggle.py \
    youtube-dl/youtube_dl/extractor/tonline.py \
    youtube-dl/youtube_dl/extractor/toutv.py \
    youtube-dl/youtube_dl/extractor/toypics.py \
    youtube-dl/youtube_dl/extractor/traileraddict.py \
    youtube-dl/youtube_dl/extractor/trilulilu.py \
    youtube-dl/youtube_dl/extractor/trutv.py \
    youtube-dl/youtube_dl/extractor/tube8.py \
    youtube-dl/youtube_dl/extractor/tubitv.py \
    youtube-dl/youtube_dl/extractor/tudou.py \
    youtube-dl/youtube_dl/extractor/tumblr.py \
    youtube-dl/youtube_dl/extractor/tunein.py \
    youtube-dl/youtube_dl/extractor/turbo.py \
    youtube-dl/youtube_dl/extractor/turner.py \
    youtube-dl/youtube_dl/extractor/tutv.py \
    youtube-dl/youtube_dl/extractor/tv2.py \
    youtube-dl/youtube_dl/extractor/tv3.py \
    youtube-dl/youtube_dl/extractor/tv4.py \
    youtube-dl/youtube_dl/extractor/tva.py \
    youtube-dl/youtube_dl/extractor/tvanouvelles.py \
    youtube-dl/youtube_dl/extractor/tvc.py \
    youtube-dl/youtube_dl/extractor/tvigle.py \
    youtube-dl/youtube_dl/extractor/tvland.py \
    youtube-dl/youtube_dl/extractor/tvnoe.py \
    youtube-dl/youtube_dl/extractor/tvp.py \
    youtube-dl/youtube_dl/extractor/tvplay.py \
    youtube-dl/youtube_dl/extractor/tvplayer.py \
    youtube-dl/youtube_dl/extractor/tweakers.py \
    youtube-dl/youtube_dl/extractor/twentyfourvideo.py \
    youtube-dl/youtube_dl/extractor/twentymin.py \
    youtube-dl/youtube_dl/extractor/twentytwotracks.py \
    youtube-dl/youtube_dl/extractor/twitch.py \
    youtube-dl/youtube_dl/extractor/twitter.py \
    youtube-dl/youtube_dl/extractor/udemy.py \
    youtube-dl/youtube_dl/extractor/udn.py \
    youtube-dl/youtube_dl/extractor/uktvplay.py \
    youtube-dl/youtube_dl/extractor/unistra.py \
    youtube-dl/youtube_dl/extractor/uol.py \
    youtube-dl/youtube_dl/extractor/uplynk.py \
    youtube-dl/youtube_dl/extractor/urort.py \
    youtube-dl/youtube_dl/extractor/urplay.py \
    youtube-dl/youtube_dl/extractor/usanetwork.py \
    youtube-dl/youtube_dl/extractor/usatoday.py \
    youtube-dl/youtube_dl/extractor/ustream.py \
    youtube-dl/youtube_dl/extractor/ustudio.py \
    youtube-dl/youtube_dl/extractor/varzesh3.py \
    youtube-dl/youtube_dl/extractor/vbox7.py \
    youtube-dl/youtube_dl/extractor/veehd.py \
    youtube-dl/youtube_dl/extractor/veoh.py \
    youtube-dl/youtube_dl/extractor/vessel.py \
    youtube-dl/youtube_dl/extractor/vesti.py \
    youtube-dl/youtube_dl/extractor/vevo.py \
    youtube-dl/youtube_dl/extractor/vgtv.py \
    youtube-dl/youtube_dl/extractor/vh1.py \
    youtube-dl/youtube_dl/extractor/vice.py \
    youtube-dl/youtube_dl/extractor/viceland.py \
    youtube-dl/youtube_dl/extractor/vidbit.py \
    youtube-dl/youtube_dl/extractor/viddler.py \
    youtube-dl/youtube_dl/extractor/videa.py \
    youtube-dl/youtube_dl/extractor/videodetective.py \
    youtube-dl/youtube_dl/extractor/videofyme.py \
    youtube-dl/youtube_dl/extractor/videomega.py \
    youtube-dl/youtube_dl/extractor/videomore.py \
    youtube-dl/youtube_dl/extractor/videopremium.py \
    youtube-dl/youtube_dl/extractor/videopress.py \
    youtube-dl/youtube_dl/extractor/vidio.py \
    youtube-dl/youtube_dl/extractor/vidme.py \
    youtube-dl/youtube_dl/extractor/vidzi.py \
    youtube-dl/youtube_dl/extractor/vier.py \
    youtube-dl/youtube_dl/extractor/viewlift.py \
    youtube-dl/youtube_dl/extractor/viewster.py \
    youtube-dl/youtube_dl/extractor/viidea.py \
    youtube-dl/youtube_dl/extractor/viki.py \
    youtube-dl/youtube_dl/extractor/vimeo.py \
    youtube-dl/youtube_dl/extractor/vimple.py \
    youtube-dl/youtube_dl/extractor/vine.py \
    youtube-dl/youtube_dl/extractor/viu.py \
    youtube-dl/youtube_dl/extractor/vk.py \
    youtube-dl/youtube_dl/extractor/vlive.py \
    youtube-dl/youtube_dl/extractor/vodlocker.py \
    youtube-dl/youtube_dl/extractor/vodplatform.py \
    youtube-dl/youtube_dl/extractor/voicerepublic.py \
    youtube-dl/youtube_dl/extractor/voxmedia.py \
    youtube-dl/youtube_dl/extractor/vporn.py \
    youtube-dl/youtube_dl/extractor/vrt.py \
    youtube-dl/youtube_dl/extractor/vube.py \
    youtube-dl/youtube_dl/extractor/vuclip.py \
    youtube-dl/youtube_dl/extractor/vvvvid.py \
    youtube-dl/youtube_dl/extractor/vyborymos.py \
    youtube-dl/youtube_dl/extractor/vzaar.py \
    youtube-dl/youtube_dl/extractor/walla.py \
    youtube-dl/youtube_dl/extractor/washingtonpost.py \
    youtube-dl/youtube_dl/extractor/wat.py \
    youtube-dl/youtube_dl/extractor/watchindianporn.py \
    youtube-dl/youtube_dl/extractor/wdr.py \
    youtube-dl/youtube_dl/extractor/webcaster.py \
    youtube-dl/youtube_dl/extractor/webofstories.py \
    youtube-dl/youtube_dl/extractor/weiqitv.py \
    youtube-dl/youtube_dl/extractor/wimp.py \
    youtube-dl/youtube_dl/extractor/wistia.py \
    youtube-dl/youtube_dl/extractor/worldstarhiphop.py \
    youtube-dl/youtube_dl/extractor/wrzuta.py \
    youtube-dl/youtube_dl/extractor/wsj.py \
    youtube-dl/youtube_dl/extractor/xbef.py \
    youtube-dl/youtube_dl/extractor/xboxclips.py \
    youtube-dl/youtube_dl/extractor/xfileshare.py \
    youtube-dl/youtube_dl/extractor/xhamster.py \
    youtube-dl/youtube_dl/extractor/xiami.py \
    youtube-dl/youtube_dl/extractor/xminus.py \
    youtube-dl/youtube_dl/extractor/xnxx.py \
    youtube-dl/youtube_dl/extractor/xstream.py \
    youtube-dl/youtube_dl/extractor/xtube.py \
    youtube-dl/youtube_dl/extractor/xuite.py \
    youtube-dl/youtube_dl/extractor/xvideos.py \
    youtube-dl/youtube_dl/extractor/xxxymovies.py \
    youtube-dl/youtube_dl/extractor/yahoo.py \
    youtube-dl/youtube_dl/extractor/yam.py \
    youtube-dl/youtube_dl/extractor/yandexmusic.py \
    youtube-dl/youtube_dl/extractor/yesjapan.py \
    youtube-dl/youtube_dl/extractor/yinyuetai.py \
    youtube-dl/youtube_dl/extractor/ynet.py \
    youtube-dl/youtube_dl/extractor/youjizz.py \
    youtube-dl/youtube_dl/extractor/youku.py \
    youtube-dl/youtube_dl/extractor/youporn.py \
    youtube-dl/youtube_dl/extractor/yourupload.py \
    youtube-dl/youtube_dl/extractor/youtube.py \
    youtube-dl/youtube_dl/extractor/zapiks.py \
    youtube-dl/youtube_dl/extractor/zdf.py \
    youtube-dl/youtube_dl/extractor/zingmp3.py \
    youtube-dl/youtube_dl/postprocessor/__init__.py \
    youtube-dl/youtube_dl/postprocessor/common.py \
    youtube-dl/youtube_dl/postprocessor/embedthumbnail.py \
    youtube-dl/youtube_dl/postprocessor/execafterdownload.py \
    youtube-dl/youtube_dl/postprocessor/ffmpeg.py \
    youtube-dl/youtube_dl/postprocessor/metadatafromtitle.py \
    youtube-dl/youtube_dl/postprocessor/xattrpp.py \
    youtube-dl/youtube_dl/__init__.py \
    youtube-dl/youtube_dl/__main__.py \
    youtube-dl/youtube_dl/aes.py \
    youtube-dl/youtube_dl/cache.py \
    youtube-dl/youtube_dl/compat.py \
    youtube-dl/youtube_dl/jsinterp.py \
    youtube-dl/youtube_dl/options.py \
    youtube-dl/youtube_dl/socks.py \
    youtube-dl/youtube_dl/swfinterp.py \
    youtube-dl/youtube_dl/update.py \
    youtube-dl/youtube_dl/utils.py \
    youtube-dl/youtube_dl/version.py \
    youtube-dl/youtube_dl/YoutubeDL.py \
    youtube-dl/setup.py \
    youtube-dl/youtube-dl
